### ISSUE TITLE
Count() called on IQueryable<T> with projection causes N1QL syntax error

### ISSUE THREAD

**Issue by jeffrymorris** [couchbaselabs/Linq2Couchbase#102]
Is this a bug? Take a query:

var beers = from beer in context.Query<Beer>()
                                where (beer.Type == "beer")
                                select new { beer.Name, Year = N1QlFunctions.DatePart(beer.Updated,     N1QlDatePart.Year) };

var results = beers.Take(1);
Assert.AreEqual(1, results.Count());

This will error with:

 {"msg":"syntax error - at as","code":3000,"name":null,"sev":0,"temp":false}

The problem seems to be that the generated N1QL query contains a Count function like this:

SELECT COUNT(`Extent1`.`name` as `name`, DATE_PART_STR(`Extent1`.`updated`, 'year') as `year`) 
FROM `beer-sample` as `Extent1` 
WHERE (`Extent1`.`type` = 'beer') LIMIT 1

The query engine doesn't like the 'as' within the COUNT function:

cbq> SELECT COUNT(`Extent1`.`name` as `name`) FROM `beer-sample` as `Extent1` WHERE (`Extent1`.`type` = 'beer') LIMIT 1;
{
    "requestID": "bbab5d10-ee72-4d36-920c-74025734c6ef",
    "errors": [
        {
            "code": 3000,
            "msg": "syntax error - at as"
        }
    ],
    "status": "fatal",
    "metrics": {
        "elapsedTime": "1.194628ms",
        "executionTime": "1.133948ms",
        "resultCount": 0,
        "resultSize": 0,
        "errorCount": 1
    }
}

cbq> SELECT COUNT(`Extent1`.`name`) FROM `beer-sample` as `Extent1` WHERE (`Extent1`.`type` = 'beer') LIMIT 1;
{
    "requestID": "d97b04b6-6c42-448f-8bd5-09f150fdf963",
    "signature": {
        "$1": "number"
    },
    "results": [
        {
            "$1": 5891
        }
    ],
    "status": "success",
    "metrics": {
        "elapsedTime": "2.59933744s",
        "executionTime": "2.599289114s",
        "resultCount": 1,
        "resultSize": 34
    }
}

Could also be a query engine bug...or not, why include the project within the COUNT?

-Jeff

**Comment by brantburnett** [comment]
@jeffrymorris 

Yeah, I think it's a bug.  Try the LINQ query without the select projection and I bet it will work.  I think we're just not handling COUNT aggregates correctly after a select projection.  As I recall, we just always put the select projection inside the COUNT statement, based on the (incorrect) theory that it will be "*" because there is no projection statement in LINQ.

Brant

**Comment by jeffrymorris** [comment]
@brantburnett -

Can this be closed?

-Jeff

**Comment by brantburnett** [comment]
@jeffrymorris 

Nope, I still need to work on this one.  I'm going to try to get it done this weekend.

Brant
