### ISSUE TITLE
The expression 'new (type: System.Linq.Expressions.MemberInitExpression) is not supported by this LINQ provider.

### ISSUE THREAD

**Issue by derix** [couchbaselabs/Linq2Couchbase#105]
I would like to get results with only partial object filled (since I have byte array that somtimes I dont want to fetch)

I try to project only specific properties:
var results = queryContext.Query<SuspectEntity>()
                .Where(me => me.Time >= from && me.Time <= to)
                .Select(se => new SuspectEntity() { ChannelId = se.ChannelId }).ToList();

Getting error:
An unhandled exception of type 'System.NotSupportedException' occurred in Remotion.Linq.dll

Additional information: The expression 'new SuspectEntity() {ChannelId = [me].ChannelId}' (type: System.Linq.Expressions.MemberInitExpression) is not supported by this LINQ provider.

**Comment by brantburnett** [comment]
@derix 

This issue should already be addressed already in the next release.  We're hoping to have it available by the end of the month.

In the meantime, instead of using the Nuget package you could build the library yourself.  There are instructions in the readme file.
