### ISSUE TITLE
Filtering by multiple keys

### ISSUE THREAD

**Issue by derix** [couchbaselabs/Linq2Couchbase#106]
Is there a way to filter by list of keys?
Meaning I have array of IDs and want to query by them.

The following is not working:
.Where(me => ids.Contains( me.Id.ToString() ))

putting manually OR between all values is working - but I need it dynamically

**Comment by brantburnett** [comment]
@derix 

The UseKeys method can be used on the main table in a query to find all documents in a list, based on their Document ID.

.Query<DocType>().UseKeys(ids)

This translates into N1QL with the very efficient USE KEYS keyword:

SELECT `Extent1`.* FROM `bucket` USE KEYS ['key1', 'key2']

Thanks,
Brant

**Comment by derix** [comment]
Many thanks.

Is the UseKeys methods exists only on latest version? Since I cannot see it in the latest version from NuGet.

**Comment by derix** [comment]
OK got it.
Note: You must import the Couchbase.Linq.Extensions namespace to use the UseKeys method.

https://github.com/couchbaselabs/Linq2Couchbase/blob/master/docs/use-keys.md
