### ISSUE TITLE
Filtering by multiple values

### ISSUE THREAD

**Issue by RafaelMontegordoFelix** [couchbaselabs/Linq2Couchbase#107]
Hi,
I'm trying to do the following:

I have multiple objects with this structure on couchbase.
{
  "someproperty": "sometext",
  "anotherproperty": "3",
  "filterproperty": 1,
}
{
  "someproperty": "sometext",
  "anotherproperty": "3",
  "filterproperty": 2,
}

I'm trying to do this query.
```
var MultipleFilterProperties = new List<long>(){2};
var query = context.Where(q => MultipleFilterProperties.Contains(q.filterproperty));
```

Regardless of the values that MultipleFilterProperties list have, the query return all items in couchbase, filter do not occur.

Is this a limitation?
It's possible to do this with linq2couchbase?

Thanks

**Comment by brantburnett** [comment]
@RafaelMontegordoFelix 

I don't believe that this is currently supported.  We recently added [support for the IN keyword](https://github.com/couchbaselabs/Linq2Couchbase/commit/050ffb051f6015e77b5503f5c4434f8f52a89e43), but this was for checking for a single value in an array nested inside your document.  I think we clearly need to implement this situation, which is the inverse.

I will see what I can do to get this complete before our next release.

Thanks,
Brant

**Comment by RafaelMontegordoFelix** [comment]
Thank you.

**Comment by brantburnett** [comment]
@RafaelMontegordoFelix 

I was able to get this working without too much trouble.  It will be included in the next release, which is coming soon.  Or you may download the master branch and build it yourself if you need it sooner.

Thanks,
Brant

**Comment by RafaelMontegordoFelix** [comment]
Nice, thank you very much.
