### ISSUE TITLE
Issue when using Linq2Couchbase with CB 4.1

### ISSUE THREAD

**Issue by eddadjei** [couchbaselabs/Linq2Couchbase#118]
When using Contains in order to achieve the IN clause, Linq2Couchbase works fine for CB 4.0 but not in CB 4.1

Here is an example

var ids = new[]{1, 2, 3};

var context = new BucketContext(_bucket);
from e in context.Query<Person>() where ids.Contains(e.Id) select e).ToList();

**Comment by brantburnett** [comment]
@eddadjei

That's unusual, I would not have expected that result.  Can you provide some more details, such as what error message you are seeing?

The generated N1QL query would also be helpful, which you can find by linking up Common.Core.Logging with your logger and logging the Couchbbase.Linq namespace at the Debug log level.

Thanks,
Brant

**Comment by eddadjei** [comment]
Please see attachment. I just created a sample application against the beer-sample bucket and am able to reproduce it. here is the code.

`    internal class Program
    {
        private static void Main(string[] args)
        {
            ClusterHelper.Initialize();
            var db = new BucketContext(ClusterHelper.GetBucket("beer-sample"));
            var beers = (from b in db.Query<Beer>()
                select b).ToList();

            var ids = beers.Select(x => x.BreweryId).Skip(0).Take(10).ToArray();

            ids.ToList().ForEach(x => Console.WriteLine("BreweryId: {0}", x));


           var allBreweryBeer = db.Query<Beer>().Where(x => ids.Contains(x.BreweryId)).ToList();

            
            Console.ReadKey();
            ClusterHelper.Close();
        }
    }`


[Couchbase41.LinqCouchbase.zip](https://github.com/couchbaselabs/Linq2Couchbase/files/158011/Couchbase41.LinqCouchbase.zip)

**Comment by brantburnett** [comment]
@eddadjei 

Thanks for the sample project, that helped a lot.  By adding this to the startup code, I was able to see query outputs as it was being built:

```
LogManager.Adapter = new ConsoleOutLoggerFactoryAdapter
{
    Level = LogLevel.Debug,
    ShowLogName = true
};
```

You can see that the N1QL query being generated for Contains is not correct at all.  The good news, however, is that this bug has already been fixed.  See Issue #107.

We're working on having a new release, with lots of new features including this one, in the next few weeks.  In the meantime, you can pull down a copy of the "master" branch and build it if you need to.  Some of the new stuff we're working on isn't complete yet, but all query-related functionality should be good to go.

Thanks,
Brant

**Comment by eddadjei** [comment]
Thanks. I guess what I don't get is, the same query works against CB 4.0 and not 4.1. could you explain this behavior?

**Comment by brantburnett** [comment]
Actually, it isn't really working against CB 4.0 either.  The difference is that the earlier version of the N1QL query engine isn't returning an error.  It just doesn't recognize that the particular syntax being sent by LINQ didn't make sense.  So your query results on CB 4.0 would not be what you expect.

Brant

**Comment by jeffrymorris** [comment]
@eddadjei -

Can we close this issue?

-Jeff

**Comment by eddadjei** [comment]
Yes. closing it
