### ISSUE TITLE
Create New Data Bucket and Document 

### ISSUE THREAD

**Issue by koonj** [couchbaselabs/Linq2Couchbase#119]
Hi, 
I'm new to nosql. I have installed Couchbase server locally.
I have created a sample mvc application and added Linq2Couchbase through NuGet. After following the example code in documentation, I can run simple select query and see the record from "beer-sample" bucket. Following is the code from Home controller 
 public ActionResult Index()
        {
            using (var cluster = new Cluster())
            {
                using (var bucket = cluster.OpenBucket("beer-sample"))
                {
                    var context = new BucketContext(bucket);

                    var query = (from beer in context.Query<Beer>()
                                where beer.Abv == 6
                                select beer).ToList();

                    return View(query);
                }
            }
            
        }

Is there any example or sample code for creating the new data bucket and document which I can see on couchbase? 

Thanks -

**Comment by akorczynski** [comment]
To create a new bucket from code:

`var cluster = new Cluster();`
`var createManager = cluster.CreateManager("Administrator", "password");`
`createManager.CreateBucket("ABucket");`
`var aBucket = cluster.OpenBucket("ABucket");``

To insert a new document:

`var doc = new Document<YourClass> { Set YourClass properties here };`
`bucket.Insert(doc);`

**Comment by koonj** [comment]
Hi, 
Thanks for the response, I could create a new bucket now but still getting error while creating document. I have following class

```
public class Product
{
    [JsonProperty("id")]
    public string Id{ get; set; }

    [JsonProperty("name")]
    public string Name{ get; set; }

    [JsonProperty("category")]
    public string Category{ get; set; }
}

var _product= new Document<Product> { ??? };
bucket.Insert(_product);

```
How do we set properties? 
Thanks

**Comment by brantburnett** [comment]
@koonj 

```
var _product= new Document<Product> {
    .Id = "some_unique_key",
    .Content = new Product() {
        // set product properties here
    }
};
bucket.Insert(_product);
```

Brant

**Comment by jeffrymorris** [comment]
@koonj - can we close this issue?

Thanks,

Jeff
