### ISSUE TITLE
Error when primary index not created, vague error message

### ISSUE THREAD

**Issue by mgroves** [couchbaselabs/Linq2Couchbase#126]
I'm a newbie to Couchbases, and I was trying to get a barebones ASP.NET MVC app going. I don't know if this is an issue with Linq2Couchbase, or the underlying .NET SDK.

I installed Couchbase locally and created a bucket. I neglected to create a primary index on it. I used an IBucketContext to query items e.g. `_context.Query<Something>().ToList()`.

When I did this, an exception was thrown of type System.Exception with the message `{"Message":null,"Code":4000,"Name":null,"Severity":0,"Temp":false}`. I couldn't find a reference to an error code 4000 (if there is a reference, please let me know!)

I was lucky enough to get ahold of @jeffrymorris and he told me to try adding an index. I used cbq to add an index like so: `CREATE PRIMARY INDEX ON `something` USING GSI;`. And then my query worked fine.

It would nice if a) the error description was a little better, b) had a more specific exception type, and/or c) there was a reference for the error code.

**Comment by jeffrymorris** [comment]
@mgroves -

This will be fixed in 2.2.7 of the SDK: https://issues.couchbase.com/browse/NCBC-1099

Thanks,

-Jeff
