### ISSUE TITLE
MonoAndroid

### ISSUE THREAD

**Issue by auriou** [couchbaselabs/Linq2Couchbase#128]
Good JOB,

Is it possible that this library is used with MonoAndroid.

thank you.

**Comment by brantburnett** [comment]
@auriou,

Thanks for the feedback, we appreciate it.  My understanding is that the current main SDK (which this library is based on) doesn't support Mono yet.  That would have to be completed before this library could support it.

I know that there is currently work in progress with the main SDK to add support for .Net core.  I'm not sure how this may or may not affect Mono support.

@jeffrymorris really knows more about this stuff than me, so perhaps he can add something.

Thanks,
Brant

**Comment by jeffrymorris** [comment]
@auriou  -

As @brantburnett mentioned, the [SDK](https://github.com/couchbase/couchbase-net-client) doesn't support Mono yet, however we have plans for a .NET Core branch and package in the future. Development efforts are currently focusing on features for the next GA version of Couchbase Server (4.5) and will likely shift to .Net Core after that (sometime this summer). Here is a Jira ticket for following: https://issues.couchbase.com/browse/NCBC-915

Note that the ticket and tasks will likely change significantly as the LOE and requirements become clearer.

Thanks, 

-Jeff

**Comment by auriou** [comment]
Great, I will follow porting DNX Core, pending I will develop a mapping / repository to expose collections of object used with linq. 
Since Xamarin is now included in Visual Studio, it becomes very interesting to develop on android or ios and using Couchbase-lite will reduce the data layer development time :-)
Thanks

**Comment by ingenthr** [comment]
You should note @auriou that Couchbase-Lite is a very different thing and this Linq2Couchbase is primarily focused on interfacing with N1QL, which is part of Couchbase Server.  My understanding is that Couchbase Lite is planning to implement LINQ directly as well, but you should check with them on roadmap.  It's here: https://github.com/couchbase/couchbase-lite-net/issues/245
