### ISSUE TITLE
WhereClause culture problem

### ISSUE THREAD

**Issue by HeuHax** [couchbaselabs/Linq2Couchbase#129]
I have run into a problem when doing this under a danish culture setting.
`var activities = DbContext.Context.Query<Location>().Where(x =>
     x.Geo.Lng > 56.5
 );`

Basically what is happening is that 56.5 is getting converted into 56,5 in the WhereClause and that makes the N1Ql query fail with the error "syntax error - at ,".

How do I fix or get around this ?

**Comment by brantburnett** [comment]
Yeah, that definitely sounds like a bug.  We need to be rendering the numeric values using the invariant culture.

If your interested, you can submit a pull request for this problem, I think the solution would be around here:
https://github.com/couchbaselabs/Linq2Couchbase/blob/master/Src/Couchbase.Linq/QueryGeneration/N1QLExpressionTreeVisitor.cs#L453

Of course, I'd be happy to take a look at it myself, as well.

In the meantime, as a workaround you should be able to avoid the problem like this:

```csharp
var cultureCache = System.Threading.Thread.CurrentThread.CurrentCulture;
System.Threading.Thread.CurrentThread.CurrentCulture = System.Globalization.CultureInfo.InvariantCulture;
try
{
    // execute the query here
    // note that the query executes when you enumerate it or call .ToList(), not when you build it
}
finally
{
    System.Threading.Thread.CurrentThread.CurrentCulture = cultureCache;
}
```

**Comment by HeuHax** [comment]
You are exactly right!
It's right at line 519:
`_expression.AppendFormat(CultureInfo.InvariantCulture, "{0}", namedParameter.Value);`

I guess this should be added everywhere where necessary, but I have only encountered the problem here so I don't know if aywhere else is necessary.

For now I say thanks !  :)
