### ISSUE TITLE
add some code samples to the README

### ISSUE THREAD

**Issue by ingenthr** [couchbaselabs/Linq2Couchbase#139]
Not super important, but I wanted to point someone to how awesome Linq2Couchbase is and noted there are no samples in the README.  It'd be great to have a quick sample or two in there.

**Comment by brantburnett** [comment]
Yeah, there are lots of samples after you follow the links in the Developer Guide section.  But a quick sample or two at the top level might help to gain traction.  Especially for users who might click away quickly.

**Comment by jeffrymorris** [comment]
Perhaps a "getting started" example is in order...

**Comment by jeffrymorris** [comment]
@brantburnett lmk if you have already picked this up, otherwise i'll push something tonight/tomorrow.

**Comment by brantburnett** [comment]
@jmorris I was thinking about it, but I haven't started anything yet.

On Tuesday, May 17, 2016, Jeffry Morris <notifications@github.com> wrote:

> @brantburnett <https://github.com/brantburnett> lmk if you have already
> picked this up, otherwise i'll push something tonight/tomorrow.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/couchbaselabs/Linq2Couchbase/issues/139#issuecomment-219900055>
>


-- 
Thanks,
Brant Burnett
CenterEdge Software
(336) 598-5934
http://centeredgesoftware.com

**Comment by brantburnett** [comment]
@jeffrymorris Sorry, wrong tag on my previous comment.

**Comment by jeffrymorris** [comment]
https://github.com/couchbaselabs/Linq2Couchbase/commit/ba8fe3ae09ac1eb8b7f46d5b56129f9a40ae10ae
