### ISSUE TITLE
Support for IN clause

### ISSUE THREAD

**Issue by mtinnes** [couchbaselabs/Linq2Couchbase#141]
I'm having trouble constructing a query to filter by a set of values. In traditional SQL I've been using the IN operator which I see has a counterpart in N1QL. Has this implemented in Linq2Couchbase? Here is the LINQ I've been trying to execute:

```
                var keys = <<some array of strings>>;
                var pings = pinglogs.Query<SupportLib.Couchbase.PingLog>()
                    .Where(o => keys.Contains(o.DeviceKey))
                    .ToList();

**Comment by brantburnett** [comment]
@mtinnes 

Are you using the latest release?  I thought that this was implemented in #107, which was included in the 1.1 release.

**Comment by mtinnes** [comment]
Yes, I'm at 1.1.0.2. The query times out with: `An unknown error occurred executing the N1QL query.`

**Comment by brantburnett** [comment]
@mtinnes 

This could be a server side issue, perhaps performance related.

1. What version of Couchbase Server are you running?
2. Can you enable logging to capture the generated N1QL query? (see #111 for an explanation on how to enable logging of queries)
3. Can you run .Explain() on the query to get the execution plan?
4. How many documents are in your bucket, and do you have an index on the DeviceKey attribute?

All of these things may help me diagnose the problem.

**Comment by mtinnes** [comment]
Thanks for the assist. Here's what I have:

Server version is `4.1.0-5005 Enterprise Edition (build-5005)`

The bucket has about 1M items with an index on deviceId

The query (partial) is: 

`SELECT `Extent1`.* FROM `pinglog` as `Extent1` WHERE `Extent1`.`deviceId` IN (['017C1B87-4359-4E0D-BAD7-EE1BFF221D3B', '042CB0A5-8888-472B-85DD-09CD25E9EAEE', '...'])`

The execution plan is as follows:

`
"results": [
        {
            "#operator": "Sequence",
            "~children": [
                {
                    "#operator": "IndexScan",
                    "index": "deviceId_index1",
                    "keyspace": "pinglog",
                    "namespace": "default",
                    "spans": [
                        {
                            "Range": {
                                "Inclusion": 1,
                                "Low": [
                                    "null"
                                ]
                            }
                        }
                    ],
                    "using": "gsi"
                },
                {
                    "#operator": "Parallel",
                    "~child": {
                        "#operator": "Sequence",
                        "~children": [
                            {
                                "#operator": "Fetch",
                                "as": "Extent1",
                                "keyspace": "pinglog",
                                "namespace": "default"
                            },
                            {
                                "#operator": "Filter",
                                "condition": "((`Extent1`.`deviceId`) in [\"017C1B87-4359-4E0D-BAD7-EE1BFF221D3B\", \"042CB0A5-8888-472B-85DD-09CD25E9EAEE\", \"061B2AAA-3539-4522-9648-AD98D412DD27\", \"0B490FB8-D284-4073-BB79-B09975B5205B\", \"0BA3B04A-2535-4794-AC31-D52782C42189\", \"0C4EDFAD-86E5-4D3C-8657-33909A1AD092\", \"0FAC727F-C105-4A95-9121-396B2625BCA1\", \"100D5C8D-E54B-4B1A-A422-51F86C0F915F\", \"10D62E75-9DAA-4E2E-B817-633EA6F91CD4\", \"136E71AF-5DB2-425D-968C-0401FCC4E687\", \"13C73C7B-96B8-4908-A646-094812FEA20E\", \"151F7788-511E-471C-8FDC-093E613A9737\", \"16337B57-B357-49D3-A355-22FB0150CC0B\", \"1A9375D4-FD31-42A9-AE65-4EFAFDD37014\", \"1F3E74A5-BA64-42CD-9B47-9E84149A56DD\", \"1F9DF9B3-9C1E-48E7-BFC3-38416303FC1F\", \"20820B23-1BD6-4805-8633-7FFA9DABA5D1\", \"216FA9FE-FCCD-41A5-8588-F9BBF0FE3053\", \"2189ED4E-4000-47B8-B66A-5BF8C12EB761\", \"21C36DFC-C5D4-4274-992B-66D5023A33EC\", \"276D42BF-38B4-46FF-A767-EA49A675CF5E\", \"285E6B2E-6150-4FC9-B9AF-A214A99B3772\", \"2BECF55C-291F-49C2-83D3-208BDB06A83D\", \"30BE5014-E5E5-4EB6-B4A0-0D5B7094DA75\", \"312A9D75-226F-4FDF-A68E-7F864FBEA37D\", \"3624C7BA-DD94-4AAF-B1FD-BE8BDCB92B0A\", \"3A48AC05-8457-4E5C-AEA0-02E78C0CC4BC\", \"3B8E9808-412F-45C0-BB2C-3EB83C04052A\", \"3BA39B56-78C4-43FB-AEB9-1655B9012216\", \"40224D41-50CD-46C1-8DBD-65A9F70C1700\", \"4490BDCC-37CF-4207-9C16-8D36AB13C8EB\", \"48F9C54C-7AE6-49C1-82F9-BA281093E8D9\", \"4CC6789F-68A7-4A06-A0D2-8896DCC7A9A5\", \"4D0BBD74-6BDA-4AFB-A066-8672C0705DA9\", \"50E4C6B8-75C9-42F3-A2CF-8C63DE8C7AE6\", \"532B3FA0-F298-4D82-AAA6-4615EF667844\", \"543F050B-9A1C-4056-8863-EA512D280570\", \"54DAFEE8-1C9D-4DF4-91BC-A1CF0C4FDB49\", \"561093FC-A7F9-4C08-BEFB-C192EA4F2CD2\", \"5B54F016-7238-4CDC-8562-4DFB695B458E\", \"5BE67E1D-2491-480F-9E4B-448DF567C248\", \"5EDCEA4B-489B-400C-A62D-AAE89816BE8A\", \"625FDB8A-33BF-46D8-B383-038BFD034049\", \"6437F89D-E2C8-42AA-B923-E3F0991379CF\", \"68F45389-0213-441B-B69D-4E35EF94BB20\", \"69B487F5-440E-4E3A-A132-5852C7C62D60\", \"6B147198-6F57-4B26-B9EE-7858E15FE5A3\", \"6F50CA58-D7FF-420F-8BC0-969224D576A6\", \"7307517F-5935-4B59-BACA-75F90AC76BA5\", \"7387D233-B288-4120-A091-37634DAC01F4\", \"73C0EDB8-1833-47A1-9216-3C0D2CF4A183\", \"74953B97-FA7C-4053-A0ED-5EBC922DE005\", \"76472B0D-03C3-4319-9257-52C43CFDD209\", \"76894FE7-DEE7-47BC-91D0-004F9308D7D2\", \"7909C506-DCD1-4697-9ABF-16A5A7C536EC\", \"79E031EE-DFF3-4381-A6FF-99B6565D6CF7\", \"7B85C4EE-F178-462B-8FEC-45AFD96E1013\", \"7D22AAE9-AAF5-4515-B6D9-F714D2221A11\", \"7D864205-A45E-46B7-8621-F99F971A55D4\", \"7DFC2413-C6DC-45A5-99EC-6676E936643F\", \"803C48D4-A9F1-4B5B-BBFC-075C0B321F46\", \"814922A0-8FC2-4902-BDC0-8AEFE4CABEE6\", \"8294E62C-F10D-4035-B091-559C05292655\", \"832CA057-B7E7-4011-80EC-8D08A19DE332\", \"84654A97-0F31-4157-A7BE-82E96367D56F\", \"84FC0444-5C18-4898-9D3F-B7E6AE693D6D\", \"8A9C751A-22F9-46AD-9216-9762DE25B3A8\", \"8AB9CD4F-BBE8-4513-BCED-F179E0B7D18E\", \"8CBECF2C-0D1E-44D6-87FC-7F3AFF58DD37\", \"915BE494-6015-43D8-8A96-E9AF6FC76439\", \"92601485-E8F2-42A5-829E-61452FA38BD6\", \"9695A0C5-7AFA-4173-A8DD-E4B2FFB6D12E\", \"A84128E8-E4EF-4C30-B357-8C3FE93E9848\", \"AA8C0B7E-2C9F-4695-91AB-6190463555FD\", \"AC3A73AF-2F6A-4671-903F-61E71BA2E07F\", \"ACB8B317-F456-4B08-A0C0-64304ED1CA30\", \"ADFCB4CF-62D5-4B8D-96C6-FB0ABB330E71\", \"B4AD7E5D-9BCC-4B5F-8867-C9AC9C7E3BFD\", \"B61314F3-1524-45E0-AFA1-B604DB523336\", \"B7AD8A01-5936-46F2-A193-AB6A3F9F2465\", \"B81EE8DA-068F-4627-951C-A4009DF9BC95\", \"BA06CAB5-49B8-42D0-B984-8BDD2006E081\", \"BAB75953-ABF0-4FB1-AD33-A3BEA1630928\", \"BB28A0C6-9710-43DB-8A15-63CFF0CB7805\", \"BD288DF5-0437-4B7B-A4B1-5705E4F37809\", \"BDE1CC47-55A9-4363-884E-7EF661D23718\", \"BE475136-8820-4BC8-BEF7-3175BD1AA701\", \"C40CC49E-A005-48E0-B576-442CFDC6CB1A\", \"C557BBFA-2EB4-43CD-A06D-8D3FB2D97770\", \"C5C92BDD-00A8-4748-A6C2-52B9A4BB4284\", \"C7E92CD9-950A-4FB1-8D39-518AE83F5DBF\", \"CA75C611-DDE3-4D56-B4EC-666DC191D085\", \"CA95B7C2-644C-489E-810C-319C8E11FBED\", \"CAC99A6B-FE9D-40CA-9F48-14CF3ADB2A76\", \"CB075665-5954-4110-B4F1-B193C8125B14\", \"CB34007F-E02C-4BFF-98E4-D5095297BE91\", \"CB6BE796-61AD-4DB9-A7EA-28A978E60E04\", \"CD2A9C2D-D1FA-456E-BF3A-5C279D2EB36E\", \"CD58B44E-A6A8-4417-B79E-07503513B65C\", \"CF501770-8E76-4B62-A67A-F1A1609FEF0D\", \"D1147D25-1F16-4285-934A-121362D1D619\", \"D27D057C-F792-44E8-9E99-8DEF3BFEACAF\", \"D30A7C87-DF34-4F11-91F0-08E1504B5B14\", \"D3E799AF-5378-41C3-B4F0-F335282F8519\", \"D51029FC-DA2A-44D0-89B0-5F8F5A6FA602\", \"D5519F14-C9BF-4575-A72E-5EB69BB4886C\", \"DABF337B-2B07-4A93-8383-E2F46708CDD1\", \"DBDB3432-2DCC-4E1C-8D05-8891AEAE45A8\", \"DEDDE284-D76E-417B-A40C-8C3940788A66\", \"DFB174E7-F627-4983-A8C6-8BDA67AC7456\", \"DFB70D39-8320-4E9A-91A9-AEED811D6E2C\", \"E1382B4E-2CDC-4D14-A10C-5A9880188DB4\", \"E3547ADA-2A11-4E10-8721-FD900FA6C982\", \"E3BD281C-4F17-454E-B9F3-5675B5F2E139\", \"E3DC990A-49B3-4BAE-A3FC-47CCCD11C448\", \"E63EA199-F3F1-4808-A0C8-82D52BEFB4D8\", \"E918C9F3-1034-45AD-A4C2-AA0F883D33A2\", \"E91FF335-92EB-4D3B-B379-58B81A757C0D\", \"EB3B87F4-0B52-44DC-B8F1-0DCA178FB2C6\", \"EF6286CB-009C-4DF3-9FDE-398011833C70\", \"F2443042-0CE2-443D-B402-0052A0407656\", \"F2A81DE9-BD82-442A-B483-D1E93E083492\", \"F2F92105-842D-407B-94A2-2232C607AFDF\", \"F49E61FF-635E-4E12-A305-6B5546AB3BF2\", \"FA4CC4E7-3F2B-4591-9115-22A850AB6B05\", \"FD628DED-C16F-4FEB-827C-65554DADC64A\", \"FD8E9CFD-364F-4ABF-925A-00E55BCEDEE1\", \"FE3BB8F0-0F14-450A-8BB3-FC2B5B4D2F96\", \"FE9FD951-BED0-44E0-ACBD-2226E9857F4C\"])"
                            },
                            {
                                "#operator": "InitialProject",
                                "result_terms": [
                                    {
                                        "expr": "`Extent1`",
                                        "star": true
                                    }
                                ]
                            },
                            {
                                "#operator": "FinalProject"
                            }
                        ]
                    }
                }
            ]
        }
    ],
    "status": "success",
    "metrics": {
        "elapsedTime": "18.65797ms",
        "executionTime": "18.58122ms",
        "resultCount": 1,
        "resultSize": 7334
    }
`

**Comment by brantburnett** [comment]
@mtinnes 

Interesting.  So the N1QL query definitely looks correct to me, and the plan is showing it using the index (it has IndexScan).  I have a couple more suggestions we can try that might help.

1.  Try running the query you provided above directly against Couchbase using the command-line "cbq" utility and see how it responds.

2.  We might be able to make the index more efficient, depending on your schema.  For example, let's say you also have a `"type": "device"` attribute or something similar, and you are only looking for these types.  And let's say that of the 1M documents, only 10,000 have this type attribute.  In that case, performance might be better if you add a `WHERE type = 'device`` clause to the index itself.  If you then add the same filter to your query it will use that smaller index.  This could be done using a `[DocumentType("device")]` attribute on the POCO, or just by adding `&& Type == 'device'` to your Where clause.

**Comment by mtinnes** [comment]
Maybe it's just too inefficient to index/filter by these GUID strings..

I've tried including timestamp in the filter but same result. I wonder if a composite index of (timestamp,deviceId) would be beneficial.

Here's the cbq output:

`{
    "requestID": "879e11af-59d2-4c40-9dc9-0e3db1af03a4",
    "signature": {
        "*": "*"
    },
    "results": [
    ],
    "errors": [
        {
            "code": 12015,
            "msg": "Index scan timed out - cause: Index scan timed out"
        }
    ],
    "status": "errors",
    "metrics": {
        "elapsedTime": "2m37.670019746s",
        "executionTime": "2m37.66995113s",
        "resultCount": 0,
        "resultSize": 0,
        "errorCount": 1
    }
}
`

**Comment by brantburnett** [comment]
@mtinnes 

Yeah, the problem is that your index is too big for the type of scan you're doing.  When you do an array contains scan like this, it has to read and use the entire index, checking each document to see if it matches.  This is different from a simple = filter or even a < or > filter, because then it can quickly jump down the B-tree to the range within the index you're interested in.

If you have a timestamp column and you're searching a small range, the index you proposed on (timestamp, deviceid) would be a good option.  That way it can jump to the range within the index using the timestamp, then filter the deviceids within that range.

**Comment by jeffrymorris** [comment]
@mtinnes -

Curious, what are you cluster specs? This is one of those things that may be solved by scaling up and out and/or applying node specific range indexes or one of the other more "advanced" indexing tricks like [covering indexes](http://developer.couchbase.com/documentation/server/current/indexes/covering-indexes.html).

**Comment by mtinnes** [comment]
We are testing with an Amazon AWS **m3.xlarge** instance (4 vCPU, 15GB memory). Just one machine, no cluster currently. Unfortunately there is no obvious way to partition the indexes, but I am able to use covering in some cases which helps alot. Indexing our timestamp with `str_to_millis(`timestamp`)` has helped quite a bit as well. Our current node is at a pretty constant 50% cpu usage which I'm sure is due to nearly constant inserts. I would guess that adding another node would take some pressure off.

**Comment by jeffrymorris** [comment]
@mtinnes - one thing you can do with multiple nodes is to make each index node aware so that in your queries you can partition the load across the cluster. Also, with Couchbase Server 4.5 which is currently in Beta and will be RTM soon there are [Memory Optimized (and Global) Indexes](http://developer.couchbase.com/documentation/server/4.5/architecture/in-memory-indexes.html?utm_source=blogs&utm_medium=link&utm_campaign=blogs).

Since this is more of an indexing issue than a Linq2Couchbase or N1QL query issue, you may be able to a better answer on the [Server forums.](https://forums.couchbase.com/c/couchbase-server)

**Comment by RafaelMontegordoFelix** [comment]
Good night,
I'm using Couchbase 4.0 CE and have the same problem.
After a few attemps i discovered that if i did the query with 16 or less keys, the query was very fast.
I'm not on couchbase right now, but if you do the explain you will see a big diference, from query with more than 16 and with 16 or less.

I tested this on a bucket with 2000000 records and i was doing a query with 3000 keys on the contains, it was giving me timeout at 10 minutes, after i found out the 16 keys trick, i change my query to:

SELECT Extent1.* FROM pinglog as Extent1 WHERE Extent1.deviceId IN (['017C1B87-4359-4E0D-BAD7-EE1BFF221D3B', '042CB0A5-8888-472B-85DD-09CD25E9EAEE', '...'])
UNION
SELECT Extent1.* FROM pinglog as Extent1 WHERE Extent1.deviceId IN (['117C1B87-4359-4E0D-BAD7-EE1BFF221D3B', '142CB0A5-8888-472B-85DD-09CD25E9EAEE', '...'])
UNION
ANOTHER 16 KEYS
.....

With this the query the response time was 9s.

Or if you want to stay with linq, you can make multiple asynchronous calls, but always breaking on 16 or less keys. (for me the time was the same)

I didn't have the time to test this on the new 4.5 Beta version. (i will test this on monday, and publish my findings on the forum).
So this can be fixed...
Any ideais why this happens? Or a better quick fix?

**Comment by jeffrymorris** [comment]
@RafaelMontegordoFelix  -

Thanks for this info, I am going to bring this up with the query folks and see what there response is. 

-Jeff

**Comment by jeffrymorris** [comment]
@RafaelMontegordoFelix @mtinnes -

The word from the server folks is that this has been improved significantly in CB 4.5; let us know what your finding are after you run it in 4.5.

-Jeff
