### ISSUE TITLE
string.StartsWith, EndsWith

### ISSUE THREAD

**Issue by rogeralsing** [couchbaselabs/Linq2Couchbase#145]
Any plans to include string.StartsWith or string.EndsWith ?
Currently we have to emulate this using `string.Substring(0,x.Length) == x` which doesnt read very well

**Comment by brantburnett** [comment]
@rogeralsing 

Your right, that's an oversight.  Also, now that I look at it regular Contains only supports passing constants, not dynamic expressions.  Let me see what I can do with this.

**Comment by brantburnett** [comment]
@rogeralsing 

See pull #146, that should give you the functionality you're looking for in the next release.  In the meantime, you can pull that down and build it locally if you need support sooner.

Thanks for the feedback.

Brant
