### ISSUE TITLE
Queries fail if BucketConfiguration.PoolConfiguration.ClientConfiguration is null

### ISSUE THREAD

**Issue by rogeralsing** [couchbaselabs/Linq2Couchbase#149]
This should probably be fixed in the core SDK but IMO, the Linq Provider needs to have better fault handling for it.

lets assume the following code

```csharp
var config = new ClientConfiguration()
{
    BucketConfigs = new Dictionary<string, BucketConfiguration>
    {
        {"MyBucket", new BucketConfiguration
        {
            BucketName = "MyBucket",
            Username = "Foo",
            Password = "Bar",
            PoolConfiguration = new PoolConfiguration
            {
                  MinSize = 1,
                  MaxSize = 10,
            }
        } }
    }
};
var cluster = new Cluster(config);
var bucket = cluster.OpenBucket("MyBucket");
var context = new BucketContext(bucket);
```

That code will throw a null ref exception when you try to query the database.
This is because of this line:

```csharp
        //BucketContext.cs

        public ClientConfiguration Configuration
        {
            get { return _bucket.Configuration.PoolConfiguration.ClientConfiguration; }
        }
````
Where `ClientConfiguration` is `null`
The client config is null because there is a back-reference from `PoolConfiguration` to `ClientConfiguration`.

In order to fix the issue, one need to set that back-reference manually:

`config.BucketConfig["MyBucket"].PoolConfiguration = config;`

This was somewhat of a pain to find, but IMO, the Linq provider could throw early with a clear error message if the `bucket.Configuration.PoolConfiguration.ClientConfiguration` is null already when clreading the BucketContext.

And the real fix should probably be to make the SDK handle all the back-references internally.
Because as it is right now, it's sort of shaky if the end user needs to wire it up themselves. even possible to point it back to a completely different config.

**Comment by brantburnett** [comment]
@rogeralsing 

You make some good points.  We should definitely look at plugging this hole.  In the meantime, I'd suggest another way of wiring up your configuration.

In more recent versions of the SDK, there is support for a new configuration concept, CouchbaseClientDefinition.  It has child objects BucketDefinition and ConnectionPoolDefinition.  These classes are designed to represent POCO configurations, so they can be read from a variety of configuration formats, such as JSON.  This is much more flexible than the XML configuration section approach.  But they'd also be great for building the configuration in code.  They should also ensure that the wireup is done correctly.

Here is an example, based on your example above.  I'm doing this in GitHub, so forgive any typos:

```csharp
var config = new CouchbaseClientDefinition()
{
    Buckets = new List<BucketDefinition>
    {
        new BucketDefinition
        {
            Name = "MyBucket",
            Password = "Bar",
            ConnectionPool = new ConnectionPoolConfiguration
            {
                  MinSize = 1,
                  MaxSize = 10
            }
        }
    }
};
var cluster = new Cluster(config);
var bucket = cluster.OpenBucket("MyBucket");
var context = new BucketContext(bucket);
```

If you want to see reading the config from JSON, you can see how it was done in the integration tests using Microsoft.Extensions.Configuration: https://github.com/couchbase/couchbase-net-client/blob/master/Src/Couchbase.IntegrationTests/Utils/TestConfiguration.cs#L66

Thanks,
Brant

**Comment by jeffrymorris** [comment]
@rogeralsing  -

I created a ticket for the SDK: https://issues.couchbase.com/browse/NCBC-1156

Thanks,

Jeff
