### ISSUE TITLE
List/Array operations fail if Serializer uses TypeNameHandling.All

### ISSUE THREAD

**Issue by rogeralsing** [couchbaselabs/Linq2Couchbase#151]
This is not a bug in the Linq2Couchbase framework per se, so sorry if this is somewhat of a stretch.
But if you use the default serializer and instruct Json.NET to use `TypeNameHandling.All` for polymorphic support in documents.

Then the Array and List operations stop working in the Linq provider.
This is due to how Json.NET emits the document.

Normally, a list would be serialized as:

```json
{
    "myListProperty" : [1,2,3,4,5]
}
``` 

But with `TypeNameHandling.All`, this becomes:
```json
{
    "myListProperty" : {
         "$type": "System.Collections.Generic.blablabla`string",
         "$items": [1,2,3,4,5]
    }
}
``` 
So structurally, the "myListProperty" is no longer a JSON array, but an object with the array embedded.
IMO, there could be some more helpful errors for this, as it is not uncommon that many devs default to `TypeNameHandling.All`.
Changing to `TypeNameHandling.Objects` fixes this problem.
But maybe the Linq provider, or even the SDK should warn/throw on if this setting is used, as the structure of the documents will not be what you'd expect.

**Comment by brantburnett** [comment]
@rogeralsing 

Unfortunately, Linq2Couchbase is designed to be serializer agnostic.  It doesn't really have any specific implementations to Json.net serialization, so I'm not sure how we could test for settings like this easily.  And I'm sure there are dozens of settings that might have similar effects, for both Json.net and other serialization libraries that may be used.

However, I think documenting this is certainly a good idea.  Json.net will probably be the most common use case, so including some serialization gotchas in a doc file would probably be helpful.

Brant

**Comment by jeffrymorris** [comment]
@rogeralsing @brantburnett - documentation is probably the bet we could do here. Unfortunately, you lose a little control with abstractions and Linq2Couchbase is one big abstraction over N1QL/Couchbase.
