### ISSUE TITLE
Generated Queries Don't Allow The Use Of Array Indexes

### ISSUE THREAD

**Issue by brantburnett** [couchbaselabs/Linq2Couchbase#153]
https://forums.couchbase.com/t/array-indexes-and-linq/9043/11

The extent name used in the ARRAY clause when making the index must match the name used in the generated query.  Currrently, extent names are always sequentially numbered in the generated query.

**Comment by brantburnett** [comment]
Resolved by pull #154

**Comment by jeffrymorris** [comment]
@brantburnett faster than me!
