### ISSUE TITLE
Multiple Nest Levels

### ISSUE THREAD

**Issue by cspaniard** [couchbaselabs/Linq2Couchbase#158]
Hello,

We are in the process of learning Couchbase/Linq2Couchbase and evaluating if we can integrate it in our environment.

We need to be able to work will "normalized tables" or document types. We also need the data to be returned as a hierarchical structure to any reasonable level of nesting.

We looked and looked and we could not find a documented solution to nest more than 2 entities.

Let me explain, we did set up a testing, but feasible, scenario:

```
Companies --> Customers --> Orders
```

_Each Company has Customers and each customer has Orders_. Each entity is stored normalized in its own document type for storage.

It is reasonable to be able to ask the DB to return a list of Companies with its Customers nested, and each Customer with all his/her Orders nested within. All in one query and one list of nested documents.

Can Linq2Couchbase handle this situation ? We got it working great nesting 2 entities, but wee need more levels.

Furthermore, it is reasonable to assume that we should be able to filter at any level (pseudo-code):

```SQL
Select Company
nest Customer
nest Order
where Customer.State = "XYZ"
and Order.Date >= "01/01/2016"
```

If Linq2Couchbase can handle this, please show us how... ;)

TIA,
David

**Comment by brantburnett** [comment]
@cspaniard 

To the best of my knowledge, you should be able to nest multiple times, so long as you are able to read or build an array of the keys to be nested from the parent document in the hierarchy.  That being said, I haven't personally tried it.  Can you provide an example LINQ query that you are trying to use that doesn't appear to be working?

Also, yes you should be able to filter on the fields at any level of the nest.  Just note that only filters on the top level of the nest (customer in your example) will be useful for selecting indexes for performance.  There are ways to improve upon this in Couchbase Server 4.5, and instead use indexes on a document lower in the tree.  It's a bit trickier, but let me know if you need this and I can help with that as well.

Brant

**Comment by cspaniard** [comment]
Hi @brantburnett 

Thanks for the quick response....

In the Linq world I don't know there to put the 2nd .LeftOuterNest

This works great for a 2 way nest between `Company` and `Customer`:

```C#
var myQuery = myContext
                .Query<Company>()
                .ScanConsistency(ScanConsistency.RequestPlus)
                .LeftOuterNest(myContext.Query<Customer>(),
                    company => company.CustomerKeys,
                    (company, customers) => new { Company = company, Customers = customers.ToList() });
```

I don't know where to go from here since if I try to place another `.LeftOuterNest` it takes `Company` as base reference for the Extension Method and not `Customer`.

In the Entity Framework world this issue gets solved with the difference between `.Include` vs `.ThenInclude` extension methods to reference the _Customer_ and take it from there.

How do you do something like that in Linq2Cauchbase ?  ;)

How do you write a Nest from `Company` to `Customer` to `Order` ?

TIA,
David

**Comment by brantburnett** [comment]
@cspaniard 

Give me some time to experiment and I'll let you know.  I believe that the second Nest should probably take place inside the project of the first LeftOuterNest, instead of .ToList().  Or perhaps without using .ToList() at all and then outside of the LeftOuterNest.  I'll see what I can come up with.

Thanks,
Brant

**Comment by brantburnett** [comment]
@cspaniard 

I haven't had any luck yet because I'm still trying to figure out the best N1QL query to write for this scenario.  Once I have a better answer there, I can try to extrapolate the best way to write the LINQ query, and to see if any Linq2Couchbase changes are required to support it.

The related forum post is here: https://forums.couchbase.com/t/multi-level-nest-statements/10147

Thanks,
Brant

**Comment by cspaniard** [comment]
Hi @brantburnett 

Thanks for taking this much interest with this issue.

I looked (and responded) to your thread on the forums. Great question.

The proposed solution uses sub-queries, but I think I read somewhere that Link2Couchbase does not support them yet.... Is that the case?

It feels strange, since I come from a strong relational background, to run into these issues that might sound silly to experienced engineers, but I just don't have document DBs experience. ;) 

So... As we stand, can we do it from Linq ? Or should we use SELECTs for multiple level nesting ?

Again... TIA,
David

**Comment by brantburnett** [comment]
@cspaniard 

Yes, Linq2Couchbase does support subqueries.  Within your select projection, you just perform another query and use the .UseKeys statement.  Give it a shot and see if you can get it to work, if not I'll be happy to play around with it some.  Here are the docs on the UseKeys statement as relates to subqueries: https://github.com/couchbaselabs/Linq2Couchbase/blob/master/docs/use-keys.md#subqueries

Thanks,
Brant

**Comment by cspaniard** [comment]
hi @brantburnett 

This is what I came up with

```c#
var myQuery = from myCompany in myContext.Query<Company>()
              select new
              {
                  Company = myCompany,
                  CustomerWithOrders =
                  (from myCustomer in myContext.Query<Customer>().UseKeys(myCompany.CustomerKeys)
                   select new
                   {
                       Customer = myCustomer,
                       Orders = (from myOrder in myContext.Query<Order>().UseKeys(myCustomer.OrderKeys)
                                 select myOrder).ToList()
                   }).ToList()
              };
```

I think this would be the "right" way to do it in LINQ.... Please any comments would be greatly appreciated (optimizations, etc...)

Once again... thank you so much for all the time you put into this...
David

**Comment by brantburnett** [comment]
@cspaniard 

Yes, that looks correct to me.  If you want to turn on logging and log the actual N1QL query executed, I can look at that as well to make sure I don't see any issues.

**Comment by cspaniard** [comment]
@brantburnett 

I did the best I could to reformat to "sanity" ;)

Generated query: 

```sql
SELECT `Extent1` as `company`, 
  (SELECT `Extent2` as `customer`, 
    (SELECT `Extent3`.* FROM `listin` as `Extent3` USE KEYS `Extent2`.`orderKeys` 
     WHERE (`Extent3`.`type` = 'Order')) as `orders` FROM `listin` as `Extent2` USE KEYS `Extent1`.`customerKeys` 
   WHERE (`Extent2`.`type` = 'Customer')) as `customerWithOrders` FROM `listin` as `Extent1` 
WHERE (`Extent1`.`type` = 'Company')
 ```

**Comment by brantburnett** [comment]
@cspaniard 

Yeah, that looks good to me.  The extra type filters are a bit redundant, but expected due to the Linq2Couchbase design.  And frankly a good backstop in case of strange data in the bucket.

Brant

**Comment by cspaniard** [comment]
@brantburnett 

Great... I would agree... I dont think those extra "type" checks are in the way. As you said a good backstop, just in case ;)

I think we can close this thread since this issue is now well investigated... 

Thank you so, so much...
David
