### ISSUE TITLE
Wrong spelling in file name aysnc-queries.md

### ISSUE THREAD

**Issue by cspaniard** [couchbaselabs/Linq2Couchbase#159]
Hi,

There is a problem with the spelling of the file **aysnc-queries.md** in the `Linq2Couchbase/docs/` path.

The link _Asynchronous Queries_ in the _Developer Guide_ seems to point to the right speeling of the file which is **async-queries.md** and therefore, the link is broken.

Just FYI... ;)
David

**Comment by brantburnett** [comment]
@cspaniard 

Thanks for letting us know!  Should be fixed now.

Brant
