### ISSUE TITLE
Change Tracking Is Incompatible With SDK 2.3.8

### ISSUE THREAD

**Issue by brantburnett** [couchbaselabs/Linq2Couchbase#161]
Changes in the SDK 2.3.8 have changed what is being deserialized for N1QL queries, breaking the process of creating document proxies.  When deserializing query results with change tracking enabled, an exception occurs:

TypeLoadException: Access is denied

Responsible SDK change: http://review.couchbase.org/#/c/67198/

We need to adjust the deserialization process to account for this change, and hopefully prevent similar changes from breaking this in the future.

**Comment by jeffrymorris** [comment]
Merged, thanks for the PR!
