### ISSUE TITLE
Linq2Couchbase doesn't work with Couchbase.NetClient 2.3.9

### ISSUE THREAD

**Issue by MikeGoldsmith** [couchbaselabs/Linq2Couchbase#169]
I'm unable to use Couchbase.NetClient 2.3.9 with Linq2Couchbase because it looks like the Couchbase.Linq has a hard dependency on 2.3.8 even though the dependency chain indicates >=2.3.8.

Steps to recreate:
1. Create a new console app
2. Install Linq2Couchbase via nuget (note: Couchbase.NetClient 2.3.8 is installed as part of the dependency chain)
3. In the `Main` method of the console add the following:
```
var config = new ClientConfiguration
{
    Servers = new List<Uri> {new Uri("couchbase://localhost")} //amend as needed
};
var cluster = new Cluster(config);

var context = new BucketContext(cluster.OpenBucket("default"));
```
This compiles and executes as expected.

4. Upgrade Couchbase.NetClient to 2.3.9 - now you get a compiler warning:
_The type 'IBucket' is defined in an assembly that is not referenced. You must add a reference to assembly 'Couchbase.NetClient, Version=2.3.8.0, Culture=neutral, PublicKeyToken=05e9c6b5a9ec94c2'._

**Comment by vfarah-if** [comment]
I am having this exact issue. When will support for this be available?

**Comment by MikeGoldsmith** [comment]
Hi @vfarah-if 

I'm working on trying to find the cause. I'll report back as and when I make progress.

Thanks

**Comment by brantburnett** [comment]
@MikeGoldsmith 

Normally a binding redirect would be automatically added by Nuget that would take care of this.  Seems odd.

Brant

**Comment by MikeGoldsmith** [comment]
I did try to manually add a binding redirect but it didn't help. This is what I added:
```
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Couchbase.NetClient" publicKeyToken="05e9c6b5a9ec94c2" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.3.9.0" newVersion="2.3.9.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```

**Comment by brantburnett** [comment]
@MikeGoldsmith 

Did the publicKeyToken change from 2.3.8 to 2.3.9, maybe?

**Comment by MikeGoldsmith** [comment]
@brantburnett 

Yes, you're correct. Using sn.exe I can see 2.3.8's public token is `05e9c6b5a9ec94c2` but 2.3.9 doesn't a public token because it's not strongly named.

I'll raise a ticket.

**Comment by MikeGoldsmith** [comment]
[Ticket](https://issues.couchbase.com/browse/NCBC-1233)

**Comment by jeffrymorris** [comment]
Hi Guys -

This will be resolved when v2.3.10 of the Couchbase .NET SDK is published around the first week of December. For now, a work-around is to revert back to v2.3.8 of the SDK. 

Sorry for the inconvenience,

Jeff

**Comment by vfarah-if** [comment]
Thanks very much Jeff!

**Comment by calhamdower** [comment]
I've updated and still having troubles with 2.3.10:
System.MissingMethodException occurred
  HResult=-2146233069
  Message=Method not found: 'System.Collections.Generic.List`1<Couchbase.N1QL.Error> Couchbase.N1QL.IQueryResult`1.get_Errors()'.
  Source=Couchbase.Linq
  StackTrace:
       at Couchbase.Linq.Execution.BucketQueryExecutor.ParseResult[T](IQueryResult`1 result)
       at Couchbase.Linq.Execution.BucketQueryExecutor.ExecuteCollection[T](LinqQueryRequest queryRequest)
       at Couchbase.Linq.Execution.BucketQueryExecutor.ExecuteCollection[T](QueryModel queryModel)
       at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteCollectionQueryModel[T](QueryModel queryModel, IQueryExecutor executor)
       at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteQueryModel(QueryModel queryModel, IQueryExecutor executor)
       at Remotion.Linq.QueryModel.Execute(IQueryExecutor executor)
       at Remotion.Linq.QueryProviderBase.Execute(Expression expression)
       at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
       at Remotion.Linq.QueryableBase`1.GetEnumerator()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

Anyone else having trouble. 2.3.8 working fine

This occurs for all L1nq Queries

**Comment by MikeGoldsmith** [comment]
Yes, I too get the same error. It think this is because the IQueryResult interface was modified in the Couchbase SDK. Originally the IQueryResult<T> has the property Error { get; } but it was moved onto the the IQueryResult interface.

Not sure why this has caused the Linq Provider to break, maybe it is trying to get the Errors from the IQueryResult<T> interface explicitly. I'll try to find the root.

**Comment by MikeGoldsmith** [comment]
Hmm, after simply rebuilding Couchbase.Linq with the 2.3.10 Couchbase SDK everything works as expected.

My guess is it was something to do with some Expressions trees not resolving properly because Couchbase.Linq was based on Couchbase SDK 2.3.8 and the local library has different interface definitions.

Anyway - I'm going to create a PR to update the Couchasbe SDK version 2.3.10.

**Comment by brantburnett** [comment]
@MikeGoldsmith 

I think that the SDK change was a SemVer breaking change, I think.  We may need to get the definitions back in the SDK somehow, and then do a 2.3.11 release.  This could potentially be breaking other consumers besides LINQ.

**Comment by MikeGoldsmith** [comment]
@brantburnett 

The `IQueryResult<T>` interface did change but does inherit all the removed members from the `IQueryResult` interface. I don't believe that would be a SemVer break because the full interferace inheritance would present the same API.

**Comment by brantburnett** [comment]
@MikeGoldsmith 

Unfortunately, I think it may be a binary-level SemVer break.  It's true that recompiling will fix it, but it does make previously compiled assemblies unable to be redirected to the new version using binding redirects.  Thus the problem with Linq2Couchbase.  The compiled binary is still looking for IQueryResult<T>.Errors, which doesn't exist, only IQueryResult.Errors.

This could also affect other consumers.  For example, in our shop we use NuGet packages for some of internal dependency tree.  Some of them depend on Couchbase.  If we upgrade our web application to using 2.3.10, it will actually break our application until we go back and upgrade the NuGet dependencies to 2.3.10 as well.

Brant

**Comment by MikeGoldsmith** [comment]
@brantburnett 

I understand and I've created the SDK ticket [NCBC-1252](https://issues.couchbase.com/browse/NCBC-1252) for use to investigate further.

**Comment by jeffrymorris** [comment]
@brantburnett @MikeGoldsmith @calhamdower 

Thanks for the explanation. So are options here are:

1. Revert the interface change in the SDK and push 2.3.11 (remove 2.3.10) _or_
2. Update the binaries in lc2 to 2.3.10 and push a new package to nuget.

I was thinking 2 was the best option, but @brantburnett raised some important points. 

As a take away, I believe we need to extend testing coverage to include integration testing with the published l2c packages.

-Jeff

**Comment by MikeGoldsmith** [comment]
Yeah, agree with increasing integration test coverage. This could be tough though as I'm sure there are many integration libraries we're not aware of.

I think in this case, reverting the SDK interface back to how it was previously is the only option until 2.4.0. We have severely limited external libraries from automatically upgrading using binding redirects.

**Comment by MikeGoldsmith** [comment]
It may also be worth updating the nuget dependencies to omit Couchbase SDK versions 2.3.9 & 2.3.10 to try and limit the 'bad' upgrades. We should be able to do that by setting the nuget version <= 2.3.8.

**Comment by MikeGoldsmith** [comment]
I've created this [ticket]() and this [commit](http://review.couchbase.org/#/c/71188/) to revert the interface back to how it was. I have also verified that reverting the interface changes did allow Linq2Couchbase to execute successfully.

**Comment by MikeGoldsmith** [comment]
2.3.11 has now been released and it is useable by Linq2Couchbase as expected.

Let me know if there are any further issues.

**Comment by vfarah-if** [comment]
Hi Mike,

Thanks very much for getting ion contact with me.

Kind regards,
Vince
