### ISSUE TITLE
Migrating to new csproj format

### ISSUE THREAD

**Issue by FernandoMorais** [couchbaselabs/Linq2Couchbase#181]
Hi all, I'm using Linq2Couchbase by direct referencing it in a netcoreapp 1.1 with VSCode on a Mac.

Since Microsoft released the final version, some changes has to be made to Couchbase.Linq.NetStandard.csproj and finaly we'll no need to use that project.json (wich do not permits link as csproj do).

I've already done it:
https://github.com/FernandoMorais/Linq2Couchbase/tree/feature/netcoreapp1.1

How could I make the PR to integrate that changes?
Do I need to follow some procedure ou just make the PR?

Thanks!

**Comment by brantburnett** [comment]
Fernando,

Yes, you can just make a pull request.

That said, we need to have some discussions over here about when we're ready to make that transition.  Once we do, VS 2015 stops working.  It's kind of painful and unfortunate that Microsoft hasn't left any avenue for backwards compatibility of repositories.

Brant

**Comment by FernandoMorais** [comment]
OK! I'll make it!

About VS 2015, we're transitioning to 2017 without problems.
Would be a better your try, in a fresh Windows VM, install VS 2017, open and build. 
The migration is working pretty well.
