### ISSUE TITLE
Slow Query using dates

### ISSUE THREAD

**Issue by RafaelMontegordoFelix** [couchbaselabs/Linq2Couchbase#183]
Hello, i have a bucket with 40M documents, i have the following index on 3 fields action, propertyId, createdDate.
When i do the query in linq2couchbase, i get this n1ql query:
SELECT `Extent1`.* FROM `OmnibeesEvents` as `Extent1` WHERE (`Extent1`.`action` = 3) 
AND (`Extent1`.`propertyId` = 1816) AND (STR_TO_MILLIS(`Extent1`.`createdDate`) >= STR_TO_MILLIS("2017-03-23T00:00:00Z")) 
AND (STR_TO_MILLIS(`Extent1`.`createdDate`) <= STR_TO_MILLIS("2017-03-24T00:00:00Z")) 
ORDER BY `Extent1`.`createdDate` DESC LIMIT 50

where the dates are converted with STR_TO_MILLIS function, and this query takes 6 seconds.

if i do the same query, but without the function STR_TO_MILLIS (without linq2couchbase):
SELECT `Extent1`.* FROM `OmnibeesEvents` as `Extent1` WHERE (`Extent1`.`action` = 3) AND (`Extent1`.`propertyId` = 1816) 
AND `Extent1`.`createdDate` >= "2017-03-23T00:00:00Z"
AND `Extent1`.`createdDate` <= "2017-03-24T00:00:00Z"
ORDER BY `Extent1`.`createdDate` DESC LIMIT 50

this takes 200ms.

The results are the same.

Is the function really necessary?
Is there a possibility of not using the function STR_TO_MILLIS in linq2couchbase?

Thanks

**Comment by MikeGoldsmith** [comment]
Hi @RafaelMontegordoFelix 

Can you show me your index definition? My guess would be that the `createdDate` in the index is not using STR_TO_MILLIS which would make the two queries query plans different.

**Comment by RafaelMontegordoFelix** [comment]
Hi, yes i was seen that right now, in the explain the createdDate field is no catch in the indexscan.
It is better to create the index with the function STR_TO_MILLIS? The index becomes faster with this?
Thanks

**Comment by MikeGoldsmith** [comment]
Yes, that's correct. If your index definition uses STR_TO_MILLIS you should then get an index hit for the faster response time.

**Comment by MikeGoldsmith** [comment]
@RafaelMontegordoFelix did that fix your issue? If yes, please can you close this issue?

Thanks

**Comment by RafaelMontegordoFelix** [comment]
I created an index with the function and the results are now the same.
Thank you.
