### ISSUE TITLE
Linq2Couchbase Lastest Version (1.3.0) Fails on Missing Remotion.Linq  during Runtime

### ISSUE THREAD

**Issue by miridfd** [couchbaselabs/Linq2Couchbase#189]
Hi,

I've downloaded the latest Linq2Couchbase nuget package (version 1.3.0), using it in a class library .NET Framework 4.6.2. (not Core!)

Compilation is just fine, but the following piece of code fails in runtime:

            return await db.Query<TSaga>()                
                .Where(query.FilterExpression)
                .Select(x => x.CorrelationId).ExecuteAsync();

While the 2 preceding lines are:

ClusterHelper.Initialize("couchbase");`
            var db = new BucketContext(ClusterHelper.GetBucket("default"));

Exception thrown:
Could not load file or assembly 'Remotion.Linq, Version=2.1.0.0, Culture=neutral, PublicKeyToken=fee00910d6e5f53b' or one of its dependencies. The system cannot find the file specified.

The nuget dependencies does not list this missing package, and more important - the "Remotion.Linq" version 2.1.0.0 does not exist on nuget.org.

Please advise,
Thanks,
Miri

**Comment by MikeGoldsmith** [comment]
Hi @miridfd 

I don't seem to have the same problem when running a test 4.6.2 console application. I can successfully execute both sync and async operations.

Do you have Remotion.Linq 2.1.0.0 listed in your packages.config? Both on [nuget.org](https://www.nuget.org/packages/Linq2Couchbase/) and in my test app a reference to 2.1.1 was added automatically. Maybe a bad binding redirect was created in your app/web.config?

**Comment by brantburnett** [comment]
@miridfd 

The problem appears to be in the build for that package.  In version 1.2.0, we were using ILRepack to embed Remotion.Linq and Castle.Core within the Linq2Couchbase assembly.  The build for 1.3.0 did not do this embedded, therefore these should have been included as dependencies on the Nuget package.

We'll probably need to release 1.3.1 to fix this problem, and either build with embedding or adjust the Nuget dependencies.

Until then, you should be able to workaround the issue by manually installing [Remotion.Linq](https://www.nuget.org/packages/Remotion.Linq/2.1.1) and [Castle.Core](https://www.nuget.org/packages/Castle.Core) in your project.

Brant

**Comment by miridfd** [comment]
Thank you, i have installed the latest Remotion.Linq, but it has been mixing up with Postsharp, resulting error compilation errors by Postsharp, that cannot be fixed (the nuget has been resolved as Other framework than specified in the package, pulling the .net core assemblies along, causing a cheos). So i rolled back, added the Remotion.Linq dll file itself to the project and referenced it.
I'll add the Castle.Core.
Thank you all.
Miri

**Comment by jeffrymorris** [comment]
@brantburnett -

Ah, yeah I see what I did...I built with `RepackedRelease` flags, but the `nuspec` file maps to the release bin folder: `bin\release` instead of `bin\repackedrelease`.

I'll push 1.3.1 sometime today.

Thanks,

Jeff

**Comment by jeffrymorris** [comment]
@brantburnett @miridfd -

Looking a bit deeper into this, I am not sure that ILRepack works with .NET Core projects (xproj) - at least using a compiler flag like we do with standard csproj projects. Since we package both .NET Full and .NET Core libraries into the same NuGet package, that is something that needs to be resolved.

A couple solutions:

- Remove ILRepack and just use standard NuGet dependencies for both .NET versions
- Remove ILRepack and just use standard NuGet dependencies for .NET Core; .NET Full uses ILRepack
- Any other ideas?

@brantburnett do we still need to use ILRepack? IIRC, we did it for a forwards compatibility issue between remotion 1.X and 2.X, is this still an issue?

-Jeff

**Comment by brantburnett** [comment]
@jeffrymorris 

ILRepack is kind of against the .NET Core approach.  My thought was the same as your two options.  Frankly, given the direction things are going re: dependency management, I'd lean towards your first option, add dependencies to both versions of the assembly.

Also, on another note 1.3.0 is also missing the CouchbaseNetClient dependency for .NET 4.5.

Brant

**Comment by jeffrymorris** [comment]
@brantburnett -

Ok, i'll push make the changes and push up a patch.

**Comment by jeffrymorris** [comment]
@miridfd @brantburnett -

1.3.1 is upon nuget.
