### ISSUE TITLE
N1QL Generated Query is not Logged

### ISSUE THREAD

**Issue by miridfd** [couchbaselabs/Linq2Couchbase#197]
Hi,

I'm trying to view the N1QL generated query, with no success.
I've followed the suggestion here: https://forums.couchbase.com/t/linq2couchbase-view-generated-n1ql-statement/9026

and the logs are indeed being logged, but there is no query.
In addition, I do not get any results, but i cannot figure out why.

Please advise,
Thanks,
Miri

**Comment by brantburnett** [comment]
@miridfd 

Confirm that you have logging for "Couchbase.Linq.Execution.BucketQueryExecutor" enabled at the Debug log level.  That's the level at which query text is logged.

Code is here for your reference:
https://github.com/couchbaselabs/Linq2Couchbase/blob/master/Src/Couchbase.Linq/Execution/BucketQueryExecutor.cs#L300

Brant

**Comment by miridfd** [comment]
yeah, i was wrong, it's ok.
Thanks
