### ISSUE TITLE
Version provider can't detect version of cluster on 5.0.0 Beta

### ISSUE THREAD

**Issue by brantburnett** [couchbaselabs/Linq2Couchbase#201]
It appears that the "/pools" endpoint has been secured for 5.0.0 Beta, so we can't use this to determine the cluster version without applying authentication.

The current behavior is that queries are run based on the down-level version 4.0.0, losing new query functionality added in  4.5.

**Comment by brantburnett** [comment]
@jeffrymorris @MikeGoldsmith 

What method would you recommend for applying authentication to the request for the "/pools" endpoint?

Some details:
1. Currently being requested using HttpClient against a random server URL from the configuration.
2. At this point we have access to the BucketConfiguration for the bucket being queried, and from that we can go up the chain all the way to the ClientConfiguration if needed.
3. Minimum SDK version is currently 2.4.5, so we do have access to the new authentication classes in the SDK.
4. Must be backwards compatible with previous Couchbase versions and with old-style configurations that don't have a password on the bucket.

Thoughts?

Thanks,
Brant

**Comment by brantburnett** [comment]
Looking at the code, I feel like we might need to expose a way to get the IAuthenticator in the SDK.  I only see ways to set it that are public.

Alternatively, we could expose at least one constructor for CouchbaseHttpClient so that we could use it externally.  That might be the cleaner option.

**Comment by jeffrymorris** [comment]
@brantburnett -

Yeah, this for RBAC. The SDK has switched over to use the IAuthenticator interface for authenticating a bucket. Support was added in 2.4.4: https://issues.couchbase.com/browse/NCBC-1341

Instead of making server "versioning" part of Linq2Couchbase, perhaps it's something we can move over to the SDK?

-Jeff

**Comment by brantburnett** [comment]
Fixed for next release
