### ISSUE TITLE
NET Standard 2.0: Exception thrown for Linq query with WHERE clause.

### ISSUE THREAD

**Issue by jefflill** [couchbaselabs/Linq2Couchbase#207]
I just upgraded my projects to the release versions of VS 15.03 and NET Core 2.0 and am seeing the following exception thrown when attempting a Couchbase Linq query with a **WHERE** clause.

````
System.AggregateException occurred
  HResult=0x80131500
  Message=One or more errors occurred. (The type initializer for 'Couchbase.Linq.QueryGeneration.DefaultMethodCallTranslatorProvider' threw an exception.)
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Test.TypeFilterAttribute.Program.Main(String[] args) in C:\src\Linq2Couchbase\Src\Test\Program.cs:line 119

Inner Exception 1:
TypeInitializationException: The type initializer for 'Couchbase.Linq.QueryGeneration.DefaultMethodCallTranslatorProvider' threw an exception.

Inner Exception 2:
TypeInitializationException: The type initializer for 'Couchbase.Linq.QueryGeneration.MethodCallTranslators.StringTrimMethodCallTranslator' threw an exception.

Inner Exception 3:
AmbiguousMatchException: Ambiguous match found.
````
I tracked this down to the `StringTrimMethodCallTranslator.SupportedMethodsStatic` field initializer.  The problem is with the `TrimStart` and `TrimEnd` `GetMethod()` calls.  These assume that there's only one method signature for these methods but it appears that NETStandard 2.0 has added a couple additional overrides for each that allow the developer to specify the trimmed characters.

The fix is to simply specify `Type.EmptyTypes` so that the original parameter-less method should be returned.  This should be backwards compatible with older frameworks.

**Comment by jeffrymorris** [comment]
Hi @jefflill - 

The Couchbase SDK which Linq2Couchbase depends on, does not yet support Core 2.0; once that is in place L2C can also support Core 2.0. I created a[ ticket ](https://issues.couchbase.com/browse/NCBC-1487)for tracking.

**Comment by jefflill** [comment]
Cool.

CouchbaseNetClient does actually work on Core 2.0 as far as I can tell (via
the magic of backwards compatibility).  I'm running some 2.0 services on
Ubuntu right now using that client and Linq2Couchbase with my change.

--Jeff

**Comment by brantburnett** [comment]
@jeffrymorris 

Yeah, my testing so far shows the CouchbaseNetClient working on .Net Core 2.0.  Just some of the ASP.Net stuff like the caching library are having issues.  Though there might be other spots in Linq2Couchbase with problems like this, I'll try to run through some more complete tests this weekend.

**Comment by jeffrymorris** [comment]
Thanks @jefflill !
