### ISSUE TITLE
_cachedKeyProperties in BucketContext class could be static to run faster !!??

### ISSUE THREAD

**Issue by lpyedge** [couchbaselabs/Linq2Couchbase#219]
_cachedKeyProperties in BucketContext class could be static to run faster !!??

**Comment by brantburnett** [comment]
@lpyedge 

Good catch, it was intended to be but it looks like it was overlooked.  Thanks for bringing it to our attention.

**Comment by MikeGoldsmith** [comment]
Closing this issue as the fix to make CackedKeyProperties static has been merged.
