### ISSUE TITLE
function GetDocumentId in BucketContext class have to change !

### ISSUE THREAD

**Issue by lpyedge** [couchbaselabs/Linq2Couchbase#220]
A model have two primary key is normal thing .
and now the function GetDocumentId only can get the first primary key to be a id.
it's a bad idea!!
here is my new code :

        internal virtual string GetDocumentId<T>(T document)
        {
            
            var trackedNode = document as ITrackedDocumentNode;
            if ((trackedNode != null) && (trackedNode.Metadata != null))
            {
                return trackedNode.Metadata.Id;
            }

            var type = document.GetType();

            PropertyInfo[] propertyInfos;
            if (!_cachedKeyProperties.TryGetValue(type, out propertyInfos))
            {
                propertyInfos = type.GetProperties()
                    .Where(p => p.GetCustomAttribute<KeyAttribute>() != null).ToArray();

                if (propertyInfos != null)
                {
                    _cachedKeyProperties.AddOrUpdate(type, propertyInfos, (key, value) => propertyInfos);
                }
            }

            if (propertyInfos != null)
            {
                var value = type.FullName;
                foreach (var item in propertyInfos)
                {
                    value += item.GetValue(document);
                }
                if (value == null)
                {
                    throw new KeyNullException(ExceptionMsgs.KeyNull);
                }

                return value.ToString();
            }

            throw new KeyAttributeMissingException(ExceptionMsgs.KeyAttributeMissing);
        }

**Comment by brantburnett** [comment]
@lpyedge 

The code that you show above is making a lot of assumptions about how a multi-part primary key would be built up if there are multiple `[Key]` attributes.  We've tried to design the system to be as flexible as possible, and make as few opinionated decisions as we can.

We have discussed support multi-part primary keys, but it will probably be something very extensible to allow them to be built in a variety of ways.  We may also make the key generation algorithm itself pluggable, which would allow you to insert custom logic like you have above.  In the meantime, we recommend using a single `[Key]` attribute on a read-only property that builds the key.  Below is a template I commonly use.

```csharp
[DocumentTypeFilter(TypeConst)]
public class MyDocument
{
    public const string TypeConst = "mytype";

    [Key]
    public string Key => GetKey(MyDocumentId, MySecondaryDocumentId);
    public string Type => TypeConst;
    public long MyDocumentId {get; set;}
    public long MySecondaryDocumentId {get; set;}

    public static string GetKey(long myDocumentId, long mySecondaryDocumentId)
    {
        return $"{TypeConst}-{myDocumentId}-{mySecondaryDocumentId}";
    }
}
```

If you don't want the Key property serialized into the document, you can add a `[JsonIgnore]` attribute as well.
