### ISSUE TITLE
Async support

### ISSUE THREAD

**Issue by alexandremblah** [couchbaselabs/Linq2Couchbase#224]
Couchbase SDK for .NET supports async, why Linq2Couchbase don't ? :)

**Comment by brantburnett** [comment]
@alexandremblah 

Linq2Couchbase does have support for async querying.  Documentation here: https://github.com/couchbaselabs/Linq2Couchbase/blob/master/docs/async-queries.md

**Comment by alexandremblah** [comment]
My Bad :( Tks @brantburnett
