### ISSUE TITLE
Support for ANSI joins in Couchbase Server 5.5

### ISSUE THREAD

**Issue by brantburnett** [couchbaselabs/Linq2Couchbase#232]
https://blog.couchbase.com/ansi-join-support-n1ql/

- [x] Basic INNER JOIN
- [x] Basic LEFT JOIN
- [x] Basic INNER NEST
- [x] Basic LEFT OUTER NEST
- [x] USE INDEX hint on the right-hand extent
- [x] USE HASH hint
- [x] List of keys NEST
- [x] USE INDEX, USE HASH on NEST operations

**Comment by jeffrymorris** [comment]
@brantburnett with the merging of #233 can this be closed?

**Comment by brantburnett** [comment]
@jeffrymorris not quite, #233 was step one, I’ve got some more coming.  This issue is more like an epic.

**Comment by brantburnett** [comment]
I've removed the following to-dos from the list:

- RIGHT OUTER JOIN - Not possible with LINQ, just reverse the order of the extents and get a LEFT OUTER JOIN.  This is what N1QL does behind the scenes anyway, so there is no special reason to support it.
- Join on IN array clause - There is no matching LINQ construct, joins in LINQ are always equi-joins

**Comment by brantburnett** [comment]
Added "List of keys NEST" as a required feature because:

- The new LINQ syntax for ANSI NEST doesn't handle a list of keys due to LINQ limitations
- The LINQ ".Nest" and ".LeftOuterNest" extensions we add does this, but always uses the ON KEYS syntax in the output N1QL
- Per @miaobingjie The ON KEYS syntax cannot be used in combination with ANSI join syntax, so using the LINQ ".Nest" or ".LeftOuterNest" will cause failures if mixed with any other joins
