### ISSUE TITLE
consider replacing Newtonsoft.Json with Jil ?? it's more faster !!

### ISSUE THREAD

**Issue by lpyedge** [couchbaselabs/Linq2Couchbase#242]
consider replacing Newtonsoft.Json with Jil ?? it's more faster !!

**Comment by MikeGoldsmith** [comment]
Hi @lpyedge 

We use the Newstonsoft.Json throughout the SDK both for internal stuff and transcoding document contents. However, the document Transcoder is pluggable and can be swapped out to use whatever JSON library you wish.
