### ISSUE TITLE
CountAsync Support

### ISSUE THREAD

**Issue by groogiam** [couchbaselabs/Linq2Couchbase#265]
It does not appear there is way to execute count asynchronously. Would it be possible to add a CountAsync method like in EntityFramework?

**Comment by brantburnett** [comment]
@groogiam 

It is supported, we just use a slightly different approach than EF. Their approach is a bit less verbose, but requires reimplementing an Async version of every immediate execution method. Instead, we use ExecuteAsync to support all possible methods.

https://github.com/couchbaselabs/Linq2Couchbase/blob/master/docs/async-queries.md#executing-scalar-queries
