### ISSUE TITLE
String Enum conversion doesn't work for variables

### ISSUE THREAD

**Issue by bVanHertum** [couchbaselabs/Linq2Couchbase#267]
According to the docs, [Json.Net StringEnumConverter](http://www.newtonsoft.com/json/help/html/t_newtonsoft_json_converters_stringenumconverter.htm) is supported if it's used on entity level, but from my tests this isn't entirely true. Namely, if the enum value is a variable (as opposed to const), the conversion still generates an integer value in the query, which causes the query to fail.

To illustrate, some code examples. GIven a Shipment class with an enum property called ShipmentType (values Default and Pending):  the following two examples work fine:

`_context.Query<Shipment>().Where(s => s.ShipmentType == ShipmentType.Pending);`

`const ShipmentType sType = ShipmentType.Pending;`
`_context.Query<Shipment>().Where(s => s.ShipmentType == sType);`

The following, however doesn't work - the generated query will use the int value of the enum, rather than the string value:

`var sType = ShipmentType.Pending;`
`_context.Query<Shipment>().Where(s => s.ShipmentType == sType);`

This also means that you cannot query based on user input for Enum values (e.g. for API's or cmd line apps).

**Comment by brantburnett** [comment]
@bVanHertum 

There's a chance this may have been fixed by this PR, which doesn't appear to have been released yet. It included some significant rework. Any chance you can try a build of the master branch and see if it resolves your problem?

https://github.com/couchbaselabs/Linq2Couchbase/commit/d4270459fe1a60a7e6d1115559aa994f99f2af78

If not, let me know and I'll see if I can reproduce (or not) some other way.

**Comment by bVanHertum** [comment]
@brantburnett 

That did indeed fix the problem (the description of that issue pretty much matches our project setup). Any word yet on when this will make it into a new release? Thanks for the help, and the quick response.

**Comment by brantburnett** [comment]
@jeffrymorris 

Any chance we can roll a 1.4.1 release?

**Comment by jeffrymorris** [comment]
@brantburnett -

Sure, we'll push 1.4.1 next week.

-Jeff

**Comment by bVanHertum** [comment]
@jeffrymorris Hey Jeff,

I've been working with my locally built master branch for a few months now, but time to deploy is coming up, and I'd love an official package. Could you push out the 1.4.1 release anytime soon?

Thanks.

**Comment by brantburnett** [comment]
@bVanHertum 

I'm going to try to look at #268 this week for you, so maybe we should wait until after that?

**Comment by bVanHertum** [comment]
@brantburnett 

Sure thing, that works. Thanks a lot for the help.

**Comment by bVanHertum** [comment]
Hey guys,

We're planning to move the items using this to release very soon - and still have the workaround for #268 

Would it be possible to push out 1.4.1 asap?

Thanks.

**Comment by MikeGoldsmith** [comment]
Hi @bVanHertum  - 1.4.1 was released 3 days ago onto [nuget](https://www.nuget.org/packages/Linq2Couchbase/1.4.1).

If this is a pressing issue for you, please feel free to contribute a fix and we can process another maintenance release once merged / tested.

**Comment by MikeGoldsmith** [comment]
I'll try to help out @brantburnett with a fix early next week and we can push a subsequent maintenance release afterwards.

**Comment by bVanHertum** [comment]
Hey Mike,

If all is good, 1.4.1 should have the fix for this issue (not for #268). I'll do a package update and test on my local.

As I said, we've got a workaround for #268, I'm fine going to release with that.

**Comment by MikeGoldsmith** [comment]
Hi @bVanHertum - did 1.4.1 work as you expected?

**Comment by bVanHertum** [comment]
Hey @MikeGoldsmith ,

Sorry for the belated response, but 1.4.1 did indeed work as expected - we've got things running on Production now without any major problems.

Thanks.

**Comment by MikeGoldsmith** [comment]
Thanks for the update @bVanHertum
