### ISSUE TITLE
Count on array subqueries causes query generation exception

### ISSUE THREAD

**Issue by bVanHertum** [couchbaselabs/Linq2Couchbase#268]
Count seems to malfunction when used in Array subqueries. Given a document that looks like this
`{ "type": "Message", "context": [ { "Id": "1"},  {"Id", "2"}, ... ] }`

And then the following query:
`_context.Query<Message>().Where(m => m.Context.Count(c => N1QlFunctions.IsValued(c.Id)) > 2).`

This should generate a query with two parts, one of the object type (defined in DocumentFilters), one on the array inside the document to count the ones with more than 2 valued Id's. However, the query generated looks as follows:
```SELECT RAW `Extent1` FROM `bucket` as `Extent1` WHERE (`Extent1`.`type` = 'Message') AND (ARRAY * FOR `Extent2` IN `Extent1`.`context` WHEN `Extent2`.`id` IS VALUED END > 2)```

which causes N1ql to throw a parse exception. I've tried a few variations of the query, but every time I use count in an array-based subquery, the "ARRAY *" statement returns.

I believe the second part _should_ look something like this (which works fine):
```ARRAY_LENGTH(ARRAY v For v in `Extent1`.`context` when v.`id` is valued end) > 2```

**Comment by bVanHertum** [comment]
Hey there,

Is anyone looking at this? I've worked around it for now by using a raw query, but it's not exactly a nice solution.

Thanks.

**Comment by bVanHertum** [comment]
Hey everyone,

Just letting you know this still seems to be an issue in 1.4.1 - in fact, it's the sole remaining reason I need to fall back on raw queries in some places. Is this still being looked at?

Thanks.

**Comment by MikeGoldsmith** [comment]
@bVanHertum we haven't had any reports of issues regarding this until now. We'll investigate further.

ping @brantburnett @jeffrymorris

**Comment by brantburnett** [comment]
@MikeGoldsmith @bVanHertum 

I've created a pull request which should address this limitation.

**Comment by MikeGoldsmith** [comment]
Thanks @brantburnett. I've accepted the PR & merged.

**Comment by bVanHertum** [comment]
Thanks @brantburnett, @MikeGoldsmith - I'll see if I can pull the latest and plug it into our software to test this.

**Comment by MikeGoldsmith** [comment]
@bVanHertum if you confirm it solves your issue, I can publish an updated nuget package too.

**Comment by bVanHertum** [comment]
@MikeGoldsmith Just ran a few tests from a local build, and it seems to work great. The query mentioned above is working fine, and a few other cases I tested work as expected as well. So.... issue solved, I think.

Thanks again, @brantburnett

**Comment by MikeGoldsmith** [comment]
Thanks @bVanHertum - I'll schedule a maintenance release soon.

**Comment by bVanHertum** [comment]
@MikeGoldsmith Any idea on an ETA for that maintenance release? I've got code sitting ready for merging, but we need this fix so it will work.

**Comment by MikeGoldsmith** [comment]
Hi @bVanHertum - sorry for the delay!

This release got lost in a stack of other things. We'll try to organise the 1.4.2 release in the next couple of days.

**Comment by bVanHertum** [comment]
> This release got lost in a stack of other things.

I know how that goes. Thanks for the update.

**Comment by bVanHertum** [comment]
Hey @MikeGoldsmith - not to be a bother, but anything on that release yet? I'm going on vacation next week, and I should deliver that code beforehand - if the release isn't possible, I'll need to put a version onto our local artefactory.

Thanks.

**Comment by brantburnett** [comment]
Also ping @jeffrymorris

**Comment by jeffrymorris** [comment]
@bVanHertum  - 

1.4.2 is on github: https://www.nuget.org/packages/Linq2Couchbase/1.4.2

Apologies for the delay!

-Jeff
