### ISSUE TITLE
String Contains Issue

### ISSUE THREAD

**Issue by mattFronz** [couchbaselabs/Linq2Couchbase#269]
Using contains I get N1QL that looks like this:
SELECT `Extent1`.`docId` as `docId` FROM `app` as `Extent1` WHERE (`Extent1`.`type` = 'chargeDscrp') AND (`Extent1`.`docId` IS NOT MISSING) AND (((`Extent1`.`tenantName` = 'legacy') AND (CASE WHEN ((CASE WHEN (`Extent1`.`description` IS NULL) THEN NULL ELSE LOWER(`Extent1`.`description`) END IS NULL) OR FALSE) THEN NULL ELSE (LOWER(`Extent1`.`description`) LIKE '%hc%') END OR CASE WHEN ((CASE WHEN (`Extent1`.`description` IS NULL) THEN NULL ELSE LOWER(`Extent1`.`description`) END IS NULL) OR FALSE) THEN NULL ELSE (LOWER(`Extent1`.`description`) LIKE '%room%') END)) = TRUE) ORDER BY `Extent1`.`docId` ASC LIMIT 10000

With the  "= TRUE" it does not return records. If I remove the "= TRUE" I get the correct results. How can I get it to remove the CASE WHEN completely?

**Comment by brantburnett** [comment]
Can you provide the C# code that’s generating this query?

**Comment by mattFronz** [comment]
Brant,

We are using OData that uses the LinqToN1QL

Calling odata with:

https://localhost:44300/odata/ChargeDescriptions?$filter=(TenantName eq 'legacy') and (contains(tolower(Description),'hc') or contains(tolower(Description),'room'))&$top=10000

Thanks,

Matt Froncek
Research & Development | Revint Solutions
Cell: 480.577.1865
mfroncek@revintsolutions.com<mailto:mfroncek@revintsolutions.com>
[round_4_3]
Confidentiality Notice: This email message and any accompanying documents is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure, distribution, or copying is prohibited. If you are not the intended recipient, please contact our office by email or telephone at 1-855-252-7606 and immediately destroy all copies of the original message.

**Comment by brantburnett** [comment]
@mattFronz 

Unfortunately, I've found that OData is usually a problem. It tends to generate some very weird and very complicated LINQ expression trees, which when we parse then make for some weird problems. I can take a look at this particular problem, it may be fixable, but I know there are other cases (which you may or may not encounter) that are outside the scope of what we're trying to support. There are plans in the works for an EF Core provider which will probably be more compatible.

My problem is going to be getting this to reproduce, it seems complicated. Is there any chance you can provide me with a repo that reproduces the problem that I can work from?

**Comment by mattFronz** [comment]
I did end up upgrading my Couchbase to version 6.0.1 and that handles the complicated query correctly. So this was a CouchBase 5.1.x issue not a linq to Couchbase issue. 

Thanks for you responses.
