### ISSUE TITLE
Couchbase SDK for .NET v3.0 is not support!

### ISSUE THREAD

**Issue by lpyedge** [couchbaselabs/Linq2Couchbase#271]
Couchbase SDK for .NET v3.0 is not support!

**Comment by MikeGoldsmith** [comment]
Hi @lpyedge 

That is correct - .NET SDK v3.0 is currently in alpha and includes an updated API which means it's not compatible with the current Linq2Couchbase source code.

We do plan to adding support for .NET v3.0 to Linq2Couchbase but this will happen at a later time.
