### ISSUE TITLE
Problem querying for types.

### ISSUE THREAD

**Issue by asusralis** [couchbaselabs/Linq2Couchbase#276]
Here is an example of what I'm trying to doing:

```
List<Tea> t = (await (from tea in _context.Query<Tea>()
                       select tea).ExecuteAsync()).ToList();
```

This by itself returns all Tea from the databases - even without using any document filters. I only have a property named "Type" that is set to "Tea". I'm not sure how this is possible because don't you need document filters to go by type? Furthermore, when I actually do what is recommended:

```
    public class TypeDocumentFilter<T> : IDocumentFilter<T> where T : IDocumentType
    {
        private readonly string _typeName;

        public int Priority { get; set; }

        public IQueryable<T> ApplyFilter(IQueryable<T> source)
        {
            return source.Where(x => x.Type == _typeName);
        }

        public TypeDocumentFilter(string typeName)
        {
            _typeName = typeName;
        }
    }
```

```
DocumentFilterManager.SetFilter(new TypeDocumentFilter<Tea>("Tea"));
```

Now the above query returns no items. On the flip side, when I try to query for Company the same way I do Tea, nothing will be found - with or without the document filter for that type. All documents have "Type": "TypeName" on them.

**Comment by brantburnett** [comment]
The recommend approach would actually be to use the predefined DocumentTypeFilter attribute on the POCO. Do you have one of those in place?

```cs
[DocumentTypeFilter('"tea")]
public class Tea {
    // ...
}
```

**Comment by asusralis** [comment]
I do not. My models are in another project that doesn't have couchbase referenced. Is that way I'm doing it wrong? I'm still confused on how it finds all the tea without using any filters but doesn't find any when I add the filters to the static class.

**Comment by asusralis** [comment]
Just a quick update: the query grabs all document types - not just Tea. That explains my first question, but I'm still not sure why my filters are not working.

**Comment by brantburnett** [comment]
Can you provide an example document? That may help.

Thanks,
Brant

**Comment by asusralis** [comment]
Model: 
```
class Tea
{
    public string Name { get; set; }

    public string Type { get; set; } = "Tea";
}
```

Data:
{
  "Name": "Paris",
  "Type": "Tea"
},
{
  "Name": "Chun Mee",
  "Type": "Tea"
}

Returns nothing:
```
 var query = (await (from tea in _context.Query<Tea>()
                                where tea.Type == "Tea"
                                select tea).ExecuteAsync()).ToList();
```
Returns nothing: 
```
DocumentFilterManager.SetFilter(new TypeDocumentFilter<Tea>("Tea"));

var query = (await (from tea in _context.Query<Tea>()
                                select tea).ExecuteAsync()).ToList();

```

Returns all documents (including not Teas):
```
 var query = (await (from tea in _context.Query<Tea>()
                                select tea).ExecuteAsync()).ToList();
```

**Comment by brantburnett** [comment]
Your most likely problem is camel-casing of attribute names. By default, the Couchbase SDK use CamelCasePropertyNameContractResolver so that a property named "Tea" is stored as "tea" in the JSON document. This is more consistent with JSON conventions. You should either override the default serialization configuration, or change your JSON attribute name to `"type": "Tea"`.

**Comment by asusralis** [comment]
This was the problem, thanks. I just added json property attributes so they're all camel case.
