### ISSUE TITLE
Is there a way to use a delegate in a select?

### ISSUE THREAD

**Issue by asusralis** [couchbaselabs/Linq2Couchbase#277]
Take this example:

```
var query = from beer in context.Query<Beer>()
					join brewery in context.Query<Brewery>()
					on beer.BreweryId equals N1QlFunctions.Key(brewery)
					select new {beerName = beer.Name, breweryName = brewery.Name};
```

Let's say there is a CompanyName property on Beer, but it needs to be set during the join. Is there any possible to do something like this:

```
var query = from beer in _context.Query<Beer>()
                           join brewery in _context.Query<Brewery>()
                           on beer.BreweryId equals N1QlFunctions.Key(brewery)
                           select () =>
                           {
                               beer.CompanyName = brewery.Name;

                               return beer;
                           }
```

Is this possible (or something similar) without having to do two separate queries or manually setting all properties using an anonymous ?

**Comment by brantburnett** [comment]
No this is not possible. This is a limitation of LINQ as a whole (with the exception of LINQ To Objects, which runs in memory). It's is intended to run off declarative expression trees which can be translated to the backing database's query language, not against flexible programming logic.

Instead of using a Lambda, just use an object initializer.

```cs
var query = from beer in _context.Query<Beer>()
                           join brewery in _context.Query<Brewery>()
                           on beer.BreweryId equals N1QlFunctions.Key(brewery)
                           select new Beer
                           {
                               beer.Name,
                               beer.X,
                               beer.Y,
                               CompanyName = brewery.Name;
                           }
```

Unfortunately, it's a bit more verbose because you need to map each property, but it should do the job.

**Comment by asusralis** [comment]
Would it be recommended to get the values back in an anonymous type and then do something like above? I have a bunch of DTOs I need to transform my documents into which use both automapper and my own methods.

**Comment by brantburnett** [comment]
Yes, I'd typically have separate document models versus DTOs, and use AutoMapper to map between them. I'd write the query something like this:

```cs
var query = from beer in _context.Query<Beer>()
                           join brewery in _context.Query<Brewery>()
                           on beer.BreweryId equals N1QlFunctions.Key(brewery)
                           select new { beer, brewery };

var results = await query.ExecuteAsync();

var dtos = results.Select(p => DoMappingHere);
```

You can actually do anything you want with lambdas in LINQ, so long as you put it **after** the query has been executed. You can trigger query execution using ExecuteAsync, by enumerating the query, or by calling AsEnumerable to convert from an IQueryable to an IEnumerable.

**Comment by asusralis** [comment]
Awesome, I'll do that! Thanks.
