### ISSUE TITLE
Escape where

### ISSUE THREAD

**Issue by skaryshev** [couchbaselabs/Linq2Couchbase#278]
Does where statement escape reserved words in a path? I am having difficulties to query
where object.path.to.**Value** == "my value"
Queries without keywords work fine for me

Thanks.

**Comment by brantburnett** [comment]
Yes, it should escape all members, reserved keywords or not. Can you use debug logging to capture the generated query?

**Comment by skaryshev** [comment]
Gotcha, thanks! I am not sure what to do next since it is lowercasing all members but they begin with upper case in a document: Generated where is (all members in backticks)
WHERE (`Extent1`.`patientDemographics`.`patientName`.`firstGivenName`.`value` = 'skaryshev') a document path is
Extent1`.`PatientDemographics`.`PatientName`.`FirstGivenName`.`Value` 
Any help greatly appreciated.

**Comment by brantburnett** [comment]
Camel-casing members is actually a Couchbase default, and thus how the SDK is configured. You can override the Serializer in your CouchbaseClient configuration to another default, if desired. I’d recommend using the DefaultSerializer but with different settings.

**Comment by skaryshev** [comment]
Closing. Where clause escaping all members. I resolved my camel-case issue with
```
new ClientConfiguration
            {
                Serializer = () => new Couchbase.Core.Serialization.DefaultSerializer(
                new JsonSerializerSettings()
                {
                    ContractResolver = new DefaultContractResolver()
                },
                new JsonSerializerSettings()
                {
                    ContractResolver = new DefaultContractResolver()
                }),
```
My two cents on .NET SDK. It is funny when DefaultSerializer does not use DefaultContractResolver by default [https://github.com/couchbase/couchbase-net-client/blob/db07eb1be7d9a0d240f16ec5b1738950f7fbddef/Src/Couchbase/Core/Serialization/DefaultSerializer.cs#L19](url)
