### ISSUE TITLE
Improve predicate generation for composite array subqueries (or add similar support)

### ISSUE THREAD

**Issue by bVanHertum** [couchbaselabs/Linq2Couchbase#283]
This concerns queries that have selection criteria using multiple fields from an array field in a document. As detailed in the couchbase docs, the way to construct these queries and indexes is as follows:

```
CREATE INDEX idx_flight_day ON `travel-sample`
( DISTINCT ARRAY [v.flight, v.day] FOR v IN schedule END)
WHERE type = "route" ;

SELECT meta().id FROM `travel-sample`
WHERE type = "route"
AND ANY v in schedule SATISFIES [v.flight, v.day] = ["US681", 2] END;
```

The primary issue is that there's no way that I've found to write a query like the one above without resorting to raw string queries.  Writing something like :

```
bucket.Select<Route>(r => r.schedule.Any(v => v.flight = "US681" && v.day = 2)
```
results (logically enough) in:
```
SELECT * from `travel-sample` where type = "route" and any v in schedule satisfies v.flight = "US681" and v.day = 2
```
which, while similar, does not react well to the index defined above. The index is not used, and you can't build a covering index for a query like this - I'm guessing because the 'and' approach allows for much more complicated predicates than the "array equality" predicate defined above.

Unless I'm missing something, to properly support these kinds of queries, we need either a way to encode these kinds of predicates, or for the predicate interpretation to interpret the above query to the 'array equality' query (maybe by detecting the simple equalities in the query?).

**Comment by brantburnett** [comment]
Interesting. We definitely haven't developed specifically for that case. However, I think it may be doable like this as a workaround:

```cs
bucket.Select<Route>(r => r.schedule.Any(v => new [] {v.flight, v.day} == new[] {"US681", v.day = 2})
```

Can you try that and see what it does? Note that this isn't a perfect workaround because unit tests running against in-memory data stores would be doing reference equality and always return false. But if this works we may be able to implement a specialized workaround function.

**Comment by bVanHertum** [comment]
Hey Brant, just tested it, and that works exactly as expected, and creates the desired query. It may not be a perfect workaround for unit testing purposes, but our unit tests generally mock the database interactions, rather than testing them, so for our code at least, this works perfectly.

A workaround function would be even better (and perhaps hide the slightly awkward syntax), of course. 

Thanks for your help 😄

**Comment by brantburnett** [comment]
At this time I'm going to close this issue. We have a workaround, either in C# or by changing the index definition. Any change to how we generate the query would tend to break other users who built the index the other way.
