### ISSUE TITLE
Select Distinct

### ISSUE THREAD

**Issue by skaryshev** [couchbaselabs/Linq2Couchbase#286]
Is Select Distinct supported? I am getting SELECT RAW DISTINCT `Extent1`.`... resulting query running
```
db.Query<MyType>()
.Where(whereExp) 
.Select(propertyExp) // propertyExp returns primitive string type
.Distinct()
```
Thanks
Edit:
`Select(pp => new { name = pp.Blah.Name })` works with Distinct()
`Select(pp => pp.Blah.Name )` results SELECT RAW DISTINCT

**Comment by skaryshev** [comment]
Additional details:
`Select(pp => new { name = pp.Blah.Name })` works with Distinct()
`Select(pp => pp.Blah.Name ) results  SELECT` RAW DISTINCT

**Comment by brantburnett** [comment]
Is this resulting in an error executing that query? If so, can you provide it?

**Comment by skaryshev** [comment]
```
{
    "code": 3000,
    "msg": "syntax error - at DISTINCT",
    "query_from_user": "SELECT RAW DISTINCT `Extent1`.`PatientDemographics`.`PatientName`.`FirstGivenName`.`Value` FROM `XXXXX` as `Extent1` WHERE (LOWER(`Extent1`.`PatientDemographics`.`PatientName`.`FirstGivenName`.`Value`) LIKE 'tra%') LIMIT 20"
  }
```
Bucket name reducted

**Comment by brantburnett** [comment]
Looks like we have an ordering issue, when RAW is combined with DISTINCT the RAW should come second. Your workaround will work for now, we'll work on a fix.

**Comment by brantburnett** [comment]
Fixed for the next release, thanks for the bug report

https://github.com/couchbaselabs/Linq2Couchbase/pull/288
