### ISSUE TITLE
Not an issue - requesting tentative release date to support Client SDK 3.0.*

### ISSUE THREAD

**Issue by atul-tewari** [couchbaselabs/Linq2Couchbase#328]
Hello Linq2couchbase Team,
We use Linq2Couchbase.  We are moving to Couchbase 6.5.1, and are updating Couchbase .NET client SDK to 3.0.2.  However, since Linq2Couchbase is still in the process of supporting 3.+, we wanted to plan our migration.

Are we 2-4 weeks away from the first release, or is this more like 3-4 moths?

Any insight would be much appreciated!

Thanks!

**Comment by brantburnett** [comment]
@atul-tewari 

As of today, you could do a local build of Linq2Couchbase and it should be compatible with 3.0.2 of the SDK. All of the major work is complete. You can monitor the status here: https://github.com/couchbaselabs/Linq2Couchbase/milestone/4

At this point, the release is primarily held up waiting on a few breaking API changes around some of the infrequently used APIs like DocumentFilterManager. I want to get those done first to avoid another major version bump later. These changes, in turn, are waiting on the release of SDK 3.0.3. But the changes are unlikely to affect you.

As it stands, I think your 2-4 week timeline is probably tight, I believe 3.0.3 of the SDK is due in about 3 weeks-ish, and that's currently a blocker. But I definitely think we'll have an official build well before 3-4 months.

In the meantime, I'd recommend using local builds of Linq2Couchbase, or alternatively we may start looking into a beta release that isn't API surface locked.

**Comment by atul-tewari** [comment]
Thank you @brantburnett   This definitely helps.  We will follow your recommendations of local builds until a final release - much appreciated!
