### ISSUE TITLE
inconsistent str_to_millis on WHERE vs ORDER BY

### ISSUE THREAD

**Issue by monodop** [couchbaselabs/Linq2Couchbase#331]
Hi, I'm curious to know why `str_to_millis` is automatically applied in `WHERE` conditions, but not in `ORDER BY` clauses. This is causing me some issues with getting the index performance I want.

For example, if I want to filter and order by date, I might get a query that's outputted like so:

```
SELECT `Extent1`.`id`, `Extent1`.`date`, `Extent1`.`type` FROM `bucket`
WHERE STR_TO_MILLIS(`Extent1`.`date`) < 1593232009319.3325
AND `Extent1`.`type` = 'myDoc'
ORDER BY `Extent1`.`date`
LIMIT 100
```

My index looks like this:

```
CREATE INDEX myIndex ON `bucket` (str_to_millis(`date`)) WHERE `type` = 'myDoc'
```

My understanding is that the issue here is that the query plan must fetch all of the documents from the index so that it can order by `date`. I can fix this by either modifying the original query to order by `str_to_millis(date)` or to filter by `date`. In those queries the index scan only returns the correct 100 results from the index. However I'm not able to create an appropriate index that supports the generated query.

Couchbase version: 6.5.1
Couchbase.net version: 2.7.20
Linq2Couchbase version: 1.4.2

**Comment by brantburnett** [comment]
@monodop 

Thanks for bringing this to our attention, you're exactly right. I've implemented a change that will go into the next major release. Note, however, that this next major release will be compatible with Couchbase SDK 3.x only.

**Comment by monodop** [comment]
Thank you for getting this done! Looking forward to using it once it's released :)
