### ISSUE TITLE
String Operation Split() in WHERE

### ISSUE THREAD

**Issue by skaryshev** [couchbaselabs/Linq2Couchbase#337]
Please help to find a proper way to use Split() in Where clause. I am trying to
`.Where(n => n.OrganizationName.Value.Split(/* :( */).Any(t => t.ToLower().StartsWith(match)))`
All documented and undocumented overloads are to no avail: System.NotSupportedException: Could not parse expression 'n.OrganizationName.Value.Split(System.Char[])': This overload of the method 'System.String.Split' is currently not supported.

Thank you
P.S: I expect Split() translated to TOKENS N1QL function.

**Comment by brantburnett** [comment]
@skaryshev 

The code that handles splits is in this class: https://github.com/couchbaselabs/Linq2Couchbase/blob/master/Src/Couchbase.Linq/QueryGeneration/MethodCallTranslators/StringSplitMethodCallTranslator.cs

It requires that you pass a single character on which to split the string, and splits it using the N1QL `SPLIT(in_str, in_subst)` method. Note that when called on a string, TOKENS forwards to SPLIT anyway.

**Comment by skaryshev** [comment]
Passing a single space character
`.Where(n => n.OrganizationName.Value.Split(' ').Any(t => t.ToLower().StartsWith(match)))`
 I am getting build error CS0854: An expression tree may not contain a call or invocation that uses optional arguments.
Setting the optional argument explicitly
` .Where(n => n.OrganizationName.Value.Split(' ', StringSplitOptions.None).Any(t => t.ToLower().StartsWith(match)))`
I am getting a runtime error: System.NotSupportedException: Could not parse expression. :(

**Comment by brantburnett** [comment]
@skaryshev 

I believe I see the problem, newer versions of .NET Core have added more overloads to String.Split. The C# compiler is picking up those overloads instead of the one we support.

Try this as a workaround to force it to use the param array overload:

```cs
.Where(n => n.OrganizationName.Value.Split(new [] {' '}).Any(t => t.ToLower().StartsWith(match)))
```

We can also look at adding support for more overloads to improve this in a future release.

**Comment by skaryshev** [comment]
No luck here: System.NotSupportedException: Could not parse expression 'n.OrganizationName.Value.Split(value(System.Char[]))': This overload of the method 'System.String.Split' is currently not supported.

Framework/SDK is Dotnet Standard 2.1
  Stack Trace: 
    MethodCallExpressionParser.GetNodeType(MethodCallExpression expressionToParse)
    MethodCallExpressionParser.Parse(String associatedIdentifier, IExpressionNode source, IEnumerable`1 arguments, MethodCallExpression expressionToParse)
    ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)
    ExpressionTreeParser.ParseNode(Expression expression, String associatedIdentifier)
    ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)
    ExpressionTreeParser.ParseNode(Expression expression, String associatedIdentifier)
    ExpressionTreeParser.ParseTree(Expression expressionTree)
    QueryParser.GetParsedQuery(Expression expressionTreeRoot)
    SubQueryFindingExpressionVisitor.CreateSubQueryNode(MethodCallExpression methodCallExpression)
    SubQueryFindingExpressionVisitor.Visit(Expression expression)
   .... More ....

**Comment by brantburnett** [comment]
Can you provide more details about your execution environment? .Net Core 3.1? netstandard2.1 is a target for build of a library, but not for execution. Also, what language version of C# are you using to compile?

We have tests in place that test for string split functionality, and they are currently passing against .NET 4.6, .Net Core 2.0, and .Net Core 3.1. So there must be some subtle difference.

https://github.com/couchbaselabs/Linq2Couchbase/blob/release14/Src/Couchbase.Linq.UnitTests/QueryGeneration/StringTests.cs#L210-L271

**Comment by skaryshev** [comment]
I have netstandard2.1 class library wrapper around Linq2Couchbase-1.4.2 (cant find any public release of 2.x yet :( ). The wrapper is to encapsulate all LINQ expressions in lambda format. E.G: (not real)
```
GetFuzzyOrganizationNames(string match)
{
     //Some LINQ
     .Where(n => n.OrganizationName.Value.Split(new [] {' '}).Any(t => t.ToLower().StartsWith(match)))
     //more LINQ
     return result;
}
```
A caller application is netcoreapp3.1 Microsoft Unit Test.

Development is in Visual Studio 16.7.3
.Net SDK is 3.1.402
string.Split implementation is coming from C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\netstandard.dll
The only difference I see is .Net Standard 2.1

**Comment by brantburnett** [comment]
Ahhh, I see, the .Any(...) subquery is the difference. Let me look into that a bit deeper, thanks.

**Comment by brantburnett** [comment]
@skaryshev 

I've put in a PR (#338) that adds support for performing subqueries (read: more advanced filtering, sorting, .Any tests) against the array returned by String.Split.

Unfortunately, there is no workaround I could find that you can use on the 1.4.2 release. Also, note that the PR is into the next release, which is compatible with SDK 3.x. If you're using SDK 2.x then you won't be able to receive this improvement once it's released.

**Comment by skaryshev** [comment]
Impatiently looking forward 2.x release. Thanks. Closing
