### ISSUE TITLE
Version 2.0.0 which works with 3.0+ SDK 

### ISSUE THREAD

**Issue by luisjjavier** [couchbaselabs/Linq2Couchbase#351]
I would like to know if the new version will be put in nuget package and if so, when will it be.

Because when I look at it in nuget and still getting 1.4.2 version

**Comment by jeffrymorris** [comment]
@luisjjavier 

There is a beta release on NuGet: https://www.nuget.org/packages/Linq2Couchbase/2.0.0-beta.1

We should be releasing a GA sometime this year.

Jeff
