### ISSUE TITLE
Scope/Collection customization at runtime 

### ISSUE THREAD

**Issue by amaruj** [couchbaselabs/Linq2Couchbase#364]
Hi,
I saw that is was possible to specify a custom scope and collection via an attribute on the document model or via a custom BucketContext : [scopes-collections](https://github.com/couchbaselabs/Linq2Couchbase/blob/master/docs/scopes-collections.md)

However, **is it possible to specify these options at runtime ?**
(because `[CouchbaseCollection("my_scope", "my_collection")]` needs consts too work).

**Comment by brantburnett** [comment]
Yes, they can be provided at runtime via the `DocumentFilterManager` class. By default, the `FilterSetGenerator` is set to an `AttributeFilterSetGenerator` which generates filters based upon attributes on the POCOs. However, you can replace this with your own implementation, which may either replace completely or extend `AttributeFilterSetGenerator`.

To override, use the overload of `AddLinq` that accepts a configuration action. This will give access to the `DocumentFilterManager`.

```csharp
clusterOptions.AddLinq(config => config.DocumentFilterManager.FilterSetGenerator = new MyFilterSetGenerator());
```

**Comment by brantburnett** [comment]
Oh, you are correct, I misread the question. That allows customization of filters but not scopes/collections. Looking more closely, there is not currently an extension point to customize this at runtime. It is something that would need to be added.

One option might be to make this member `public`, but I'm not sure it's the best option.

https://github.com/couchbaselabs/Linq2Couchbase/blob/b4238859a486d4c63fb78493853ae93bb0837683/Src/Couchbase.Linq/BucketContext.cs#L71

Any time we're making public API changes we need to think through them carefully. It would be more complex to find some way to expose an override for the `CollectionMetadataCache`, but that might be more useful.

**Comment by amaruj** [comment]
Thanks for your answer.
An alternative solution would be to build dynamically a custom BucketContext (that inherits from BucketContext) with the desired scope and collection.
However, scope/collection customization via BucketContext works pretty well with .NET Core but not with .Net 4.8 unfortunatly (That's the issue case my collegue opened : [Crash with .Net 4.8](https://github.com/couchbaselabs/Linq2Couchbase/issues/365))

**Comment by Farooquem-XPO** [comment]
> Thanks for your answer. An alternative solution would be to build dynamically a custom BucketContext (that inherits from BucketContext) with the desired scope and collection. However, scope/collection customization via BucketContext works pretty well with .NET Core but not with .Net 4.8 unfortunatly (That's the issue case my collegue opened : [Crash with .Net 4.8](https://github.com/couchbaselabs/Linq2Couchbase/issues/365))

Can you share implementation?
