### ISSUE TITLE
Crash with .Net 4.8

### ISSUE THREAD

**Issue by mdegroux** [couchbaselabs/Linq2Couchbase#365]
Hi,

My App targets .Net Framework 4.8

I have a custom BucketContext like this:
``` csharp

    public class CibmlBucketContext : BucketContext, IDynamicBucketContext<CibmlCouchbaseModel>
    {
        public CibmlBucketContext(Couchbase.IBucket bucket) : base(bucket)
        {
        }
        [CouchbaseCollection("otr_dev21", "default")]
        public IDocumentSet<CibmlCouchbaseModel> Documents { get; set; }
    }
```

When I instanciate my context, I have this exception:
"System.Security.VerificationException: Cette opération pourrait déstabiliser le runtime.\r\n   à Initialize(BucketContext )"
![image](https://github.com/couchbaselabs/Linq2Couchbase/assets/20659365/666d872c-1d11-4aac-a216-86b20c5a935b)

**Comment by mdegroux** [comment]
As complement I found the error comes from the generated IL in CreateInitializeAction method

**Comment by brantburnett** [comment]
Do you have any additional details on that exception you can provide? The information I can find on possible causes is pretty vague, and I've reviewed the generated IL and I don't see an obvious cause.

My best guess is that this cast may be a factor: https://github.com/couchbaselabs/Linq2Couchbase/blob/b4238859a486d4c63fb78493853ae93bb0837683/Src/Couchbase.Linq/Metadata/ContextMetadata.cs#L74

It's casting the `BucketContext` to the specific type of your context `CibmlBucketContext`. Later on it's passed to the constructor for `DocumentSet<T>` which takes  `BucketContext`. I'm wondering if we need to pass the `BucketContext` argument directly without casting.

**Comment by mdegroux** [comment]
When I comment the code in property loop => no more crash
but indeed the init action do not does it's job :)

crashing:
```csharp

            foreach (var property in Properties)
            {
                // load for property setter
                il.Emit(OpCodes.Ldloc_0);


                //// load again for constructor
                //il.Emit(OpCodes.Dup);
                //il.Emit(OpCodes.Ldstr, property.CollectionInfo.Scope);
                //il.Emit(OpCodes.Ldstr, property.CollectionInfo.Collection);

                //var documentSetType = typeof(DocumentSet<>).MakeGenericType(property.DocumentType);
                //var documentSetConstructor = documentSetType.GetConstructor(DocumentSetConstructorArgumentTypes);
                //il.Emit(OpCodes.Newobj, documentSetConstructor);
                //il.Emit(OpCodes.Castclass, typeof(IDocumentSet<>).MakeGenericType(property.DocumentType));

                //var setter = property.Property.GetSetMethod();
                //il.Emit(OpCodes.Callvirt, setter);
            }
```
Not crashing
```csharp
            foreach (var property in Properties)
            {
                // load for property setter
                //il.Emit(OpCodes.Ldloc_0);


                //// load again for constructor
                //il.Emit(OpCodes.Dup);
                //il.Emit(OpCodes.Ldstr, property.CollectionInfo.Scope);
                //il.Emit(OpCodes.Ldstr, property.CollectionInfo.Collection);

                //var documentSetType = typeof(DocumentSet<>).MakeGenericType(property.DocumentType);
                //var documentSetConstructor = documentSetType.GetConstructor(DocumentSetConstructorArgumentTypes);
                //il.Emit(OpCodes.Newobj, documentSetConstructor);
                //il.Emit(OpCodes.Castclass, typeof(IDocumentSet<>).MakeGenericType(property.DocumentType));

                //var setter = property.Property.GetSetMethod();
                //il.Emit(OpCodes.Callvirt, setter);
            }
```

**Comment by brantburnett** [comment]
Can you try this instead:

```csharp
            foreach (var property in Properties)
            {
                // load for property setter
                il.Emit(OpCodes.Ldarg_0);

                // load again for constructor
                il.Emit(OpCodes.Dup);
                il.Emit(OpCodes.Ldstr, property.CollectionInfo.Scope);
                il.Emit(OpCodes.Ldstr, property.CollectionInfo.Collection);

                var documentSetType = typeof(DocumentSet<>).MakeGenericType(property.DocumentType);
                var documentSetConstructor = documentSetType.GetConstructor(DocumentSetConstructorArgumentTypes);
                il.Emit(OpCodes.Newobj, documentSetConstructor);
                il.Emit(OpCodes.Castclass, typeof(IDocumentSet<>).MakeGenericType(property.DocumentType));

                var setter = property.Property.GetSetMethod();
                il.Emit(OpCodes.Callvirt, setter);
            }
```

**Comment by mdegroux** [comment]
same problem :(

**Comment by brantburnett** [comment]
I think this may have something to do with security settings applied in .NET 4:

https://learn.microsoft.com/en-us/dotnet/api/system.reflection.emit.methodbuilder.initlocals?view=net-8.0#remarks

It appears that setting this makes the method unverifiable, thus the exception. I'm not really an expert on the security verification stuff in .NET 4, though, I think it may vary depending on the security context/settings in which you are running the application. I'm guessing you're hosting in a shared worker process in IIS?

**Comment by mdegroux** [comment]
Absolutely not :)
it's a pure console app

**Comment by mdegroux** [comment]
I found the fix, you simply need to add typeof(BucketContext) as last parameter of DynamicMethod ctor
```csharp
            var dynMethod = new DynamicMethod("Initialize", null, new[] { typeof(BucketContext) }, typeof(BucketContext))
```

doing this will let the method have the same security context as BucketContext

**Comment by mdegroux** [comment]
I have opened a pull request: https://github.com/couchbaselabs/Linq2Couchbase/pull/366
