### ISSUE TITLE
NullReferenceException randomly occurs when querying

### ISSUE THREAD

**Issue by mdegroux** [couchbaselabs/Linq2Couchbase#370]
Hi,

We randomly have a NullReferenceException when we query our couchbase server

```
System.ArgumentNullException
  HResult=0x80004003
  Message=La valeur ne peut pas être null.
Nom du paramètre : baseUri
  Source=System
  StackTrace:
   at System.Uri..ctor(Uri baseUri, String relativeUri) in f:\dd\NDP\fx\src\net\System\URI.cs:line 460
```
![image](https://github.com/couchbaselabs/Linq2Couchbase/assets/20659365/a683c35a-2b0a-46c3-b521-8351636f3fa3)

Here is what I digged

In `ClusterQueryExecuter.GenerateQuery` (Linq2Couchbase), you call `_clusterVersionProvider.GetVersionAsync().Result`

In `ClusterVersionProvider.GetVersionAsync` (CouchbaseNetClient), you build a list of uris from nodes
`_clusterContext.Nodes.Select(p => p.ManagementUri)`

Then you shuffle the uris and return the version of the first node providing it
```
            foreach (var server in servers.ToList().Shuffle())
            {
.....
                    var config = await DownloadConfigAsync(httpClient, server).ConfigureAwait(false);
.....
            }
```

If I look at the node list in ClusterContext, I have 5 nodes
![image](https://github.com/couchbaselabs/Linq2Couchbase/assets/20659365/e79fb7f6-331a-419c-addf-b185e1e6fb18)

The first one is the bootstrap and the 4 others are servers, and the bootstrap has no management uri

This is the root cause of the crash
![image](https://github.com/couchbaselabs/Linq2Couchbase/assets/20659365/f2879d7c-252f-4043-b110-06fa3af9f9a8)

I don't know if somethig is missing in configuration, or if this is a bug

**Comment by brantburnett** [comment]
Thanks so much for all of the great details! I agree that this is a bug, but it's actually a bug in the Couchbase SDK. I've filed a bug report there for tracking. I'm going to close this issue for now.

https://issues.couchbase.com/browse/NCBC-3503
