### ISSUE TITLE
Support for `DocumentFilter` with Custom Bucket Context `IDocumentSet`

### ISSUE THREAD

**Issue by xshaheen** [couchbaselabs/Linq2Couchbase#376]
Description
I've noticed that the DocumentFilter functionality currently only works with the BucketContext.Query method and does not seem to apply when using an IDocumentSet within a custom bucket context.

Use Case
In my application, I am working with a custom bucket context where I use IDocumentSet. It would be very helpful to be able to apply DocumentFilter directly on this IDocumentSet to take advantage of consistent filtering across different bucket contexts.

Expected Behavior
I expected DocumentFilter to be compatible with both BucketContext.Query and IDocumentSet, allowing seamless filtering regardless of the context.

Current Behavior
Currently, DocumentFilter only works with BucketContext.Query, making it challenging to use in custom bucket contexts that rely on IDocumentSet.

**Comment by xshaheen** [comment]
After investigation, I discovered that some LINQ methods, such as `ToListAsync`, function as expected and apply `DocumentFilter`. However, others, like `FirstAsync` and similar methods, don't apply the filter. This issue arises because of the line in the code:

https://github.com/couchbaselabs/Linq2Couchbase/blob/fd1508d2e1cb7bb9e0e3f8d22f2a7eaeac4066b7/Src/Couchbase.Linq/DocumentSet%601.cs#L55

To ensure the filter expression is applied when it exists, I think the line should be updated to `Expression = MakeQueryable().Expression;`.

**Comment by brantburnett** [comment]
> After investigation, I discovered that some LINQ methods, such as `ToListAsync`, function as expected and apply `DocumentFilter`. However, others, like `FirstAsync` and similar methods, don't apply the filter.

I agree with your assessment of the problem. However, I think the solution is a bit more complicated. If we just make the change you suggest then it will snapshot the configured filters when the `BucketContext` inherited class is created and won't pick up any changes made after that point. This may be okay, I need to consider it a bit more.

**Comment by xshaheen** [comment]
@brantburnett It's great that you caught that potential issue! Making it a computed property could be a viable solution to dynamically pick up any changes to the filters after the `BucketContext` inherited class is created. What do you think of that approach?

I’ve also created a PR and tested it in my own setup, and it works well for my use case, but I’m open to refining it if you have other ideas! #377

**Comment by brantburnett** [comment]
I'm also playing around with some ideas that would be a bit more performant, but having some trouble with infinite loops. I'm going to keep playing with it and see where I end up.

**Comment by brantburnett** [comment]
@xshaheen The scope was a bit more than I anticipated, but I'm pretty happy with the results. Can you review #378 and see what you think and if it addresses your issues?

**Comment by xshaheen** [comment]
@brantburnett I reviewed and tested it with my own use case, and it looks like a great change with noticeable performance improvements! Thanks for the effort on this; it definitely addresses my issues. I hope it gets merged soon.

**Comment by brantburnett** [comment]
> @brantburnett I reviewed and tested it with my own use case, and it looks like a great change with noticeable performance improvements! Thanks for the effort on this; it definitely addresses my issues. I hope it gets merged soon.

I'm opening it for review now and I'll see what I can make happen. Thanks.

**Comment by brantburnett** [comment]
@xshaheen Version 2.1.0 should be available now on NuGet with these changes.

**Comment by xshaheen** [comment]
great thank you.
