### ISSUE TITLE
API Cleanup - Is WhereMissing Still Necessary?

### ISSUE THREAD

**Issue by brantburnett** [couchbaselabs/Linq2Couchbase#51]
Currently, there are two different LINQ methods to add a filter to only include documents missing a particular property:

1.  Use `.WhereMissing(p => p.Property)`
2.  Use N1Ql.IsMissing(p.Property) in one of two ways:
a.  `from p in bucketContext where N1Ql.IsMissing(p.Property) select p`
b.  `.Where(p => N1Ql.IsMissing(p.Property)`

Is having two methods of doing the same thing worthwhile?  It could add to long term maintenance issues as well as cause API confusion.

1.  .WhereMissing can only be used in lambda syntax, not in C# queries
2.  The inverse N1Ql.IsNotMissing is only available using syntax 2 above
3.  The similar methods IsValued and IsNotValued are also only available using syntax 2 above
4.  It will reduce the area required for long term support if removed

Thoughts?

**Comment by jeffrymorris** [comment]
Agree, I think IsMissing is a better name.

-jeff
