### ISSUE TITLE
send creds for communication via non-secured channels

### ISSUE THREAD

**Issue by wiciul** [couchbaselabs/Linq2Couchbase#84]
Creds are not sent for bucket with password when communication with server is done via non-secured channels.

**Comment by brantburnett** [comment]
@wiciul 

I believe that this is a bug in the Couchbase Server.  @jeffrymorris recently put in a workaround for it in the main SDK, but it hasn't been released yet.

https://issues.couchbase.com/browse/NCBC-1039

Does this agree with the symptoms you're seeing?  Or do you think it's a separate issue?

**Comment by wiciul** [comment]
I don't think it is separate issue.
